/**
 * arenaSeedChallenges.data.mjs — curated initial challenge library (spec
 * §59, §18). Four genuinely discipline-specific challenges per stream (44
 * total across 11 streams) — quality over quantity. Every entry goes
 * through the SAME validateChallengeContent pipeline AI-generated content
 * does (see arenaSeedChallenges.mjs) before being persisted; nothing here
 * is special-cased or exempt from the semantic-stream/vocabulary check.
 *
 * The library is meant to grow via the AI generation fallback as real
 * weekly demand exceeds it (spec §41) — this seed only needs to be large
 * enough that most weeks don't have to lean on generation for every
 * student in every stream.
 */

export const SEED_CHALLENGES = [
  // ─── CSE ──────────────────────────────────────────────────────────────
  {
    stream: "cse",
    competency_area: "Algorithms",
    skill: "Binary Search",
    challenge_type: "debugging",
    title: "Fix the Off-By-One in a Binary Search",
    scenario: "A teammate's binary search on a sorted array of user IDs sometimes returns the wrong index or loops forever when the target is the last element. Code review found the bug is in the loop bounds and midpoint update.",
    mission: "Read the buggy implementation below, fix the off-by-one error, and print the found index (or -1) for the given target.",
    learning_objective: "Correctly reason about inclusive/exclusive loop bounds in binary search.",
    difficulty: "easy",
    estimated_minutes: 10,
    instructions: "The starter code is provided as `inputs.starterCode`. Fix it in place (you may rewrite the function body) so it correctly binary-searches `arr` for `target` and prints only the resulting index on one line. Do not change the function name or the final print statement's format.",
    inputs: {
      starterCode: "function binarySearch(arr, target) {\n  let lo = 0, hi = arr.length; // BUG: should be arr.length - 1\n  while (lo < hi) { // BUG: wrong comparison causes infinite loop / wrong bounds\n    const mid = Math.floor((lo + hi) / 2)\n    if (arr[mid] === target) return mid\n    if (arr[mid] < target) lo = mid + 1\n    else hi = mid\n  }\n  return -1\n}\nconst arr = [2, 5, 8, 12, 16, 23, 38, 45, 56, 72, 91]\nconsole.log(binarySearch(arr, 91))",
      language: "javascript",
    },
    expected_output: { stdout: "10" },
    workstation_type: "coding",
    verification_type: "test_cases",
    verification_definition: { language: "javascript", testCases: [{ expectedStdout: "10" }] },
    points: 10,
    explanation: "The last element (index 10, value 91) must be reachable — using `hi = arr.length - 1` and `lo <= hi` (or an equivalent correctly-bounded loop) fixes both the infinite loop and the missed last element.",
    tags: ["algorithms", "binary-search", "debugging"],
  },
  {
    stream: "cse",
    competency_area: "Databases",
    skill: "SQL Aggregation",
    challenge_type: "data_interpretation",
    title: "Find Customers With Duplicate Orders on the Same Day",
    scenario: "The orders team suspects a checkout bug is double-submitting orders — the same customer placing what looks like two identical orders within the same day. Before filing a bug, they need proof from the orders table.",
    mission: "Write a SQL query against the `orders` table that returns customer_id and order_date for any customer with more than one order placed on the same date.",
    learning_objective: "Use GROUP BY / HAVING to detect duplicate-pattern rows — a genuine database reasoning task, not a plain filter.",
    difficulty: "easy",
    estimated_minutes: 10,
    instructions: "Query the `orders` table (columns: id, customer_id, order_date, amount). Return customer_id and order_date for every (customer_id, order_date) pair that appears more than once.",
    inputs: {
      dataset: {
        tableName: "orders",
        columns: ["id", "customer_id", "order_date", "amount"],
        rows: [
          [1, "C1", "2026-01-01", 500], [2, "C1", "2026-01-01", 500], [3, "C2", "2026-01-01", 300],
          [4, "C3", "2026-01-02", 700], [5, "C3", "2026-01-03", 700], [6, "C4", "2026-01-02", 200], [7, "C4", "2026-01-02", 250],
        ],
      },
    },
    expected_output: { columns: ["customer_id", "order_date"], rows: [["C1", "2026-01-01"], ["C4", "2026-01-02"]] },
    workstation_type: "sql",
    verification_type: "sql_result",
    verification_definition: {
      dataset: { tableName: "orders", columns: ["id", "customer_id", "order_date", "amount"], rows: [[1, "C1", "2026-01-01", 500], [2, "C1", "2026-01-01", 500], [3, "C2", "2026-01-01", 300], [4, "C3", "2026-01-02", 700], [5, "C3", "2026-01-03", 700], [6, "C4", "2026-01-02", 200], [7, "C4", "2026-01-02", 250]] },
      expectedResult: { columns: ["customer_id", "order_date"], rows: [["C1", "2026-01-01"], ["C4", "2026-01-02"]] },
      matchMode: "unordered_rows",
    },
    points: 10,
    explanation: "GROUP BY customer_id, order_date HAVING COUNT(*) > 1 is the standard pattern for detecting duplicate-row conditions in a table — a real database-reasoning skill beyond a plain WHERE filter.",
    tags: ["databases", "sql", "group-by"],
  },
  {
    stream: "cse",
    competency_area: "Data Structures",
    skill: "Stack-Based Parsing",
    challenge_type: "debugging",
    title: "Fix an Inverted Comparison in a Balanced-Parentheses Checker",
    scenario: "A code-review tool's bracket-matching utility is supposed to check whether a string's brackets are balanced, but it's flagging valid, correctly-balanced code as broken. A teammate suspects the stack comparison logic is inverted.",
    mission: "Find and fix the inverted comparison so the function correctly reports whether the given string's brackets are balanced.",
    learning_objective: "Correctly implement stack-based matching logic and recognize an inverted boolean comparison as a subtle, common bug class.",
    difficulty: "easy",
    estimated_minutes: 10,
    instructions: "Fix the starter code so it correctly prints \"true\" or \"false\" for whether the brackets in the given string are balanced. Do not change the function name or the final print statement's format.",
    inputs: {
      starterCode: "function isBalanced(s) {\n  const stack = []\n  const pairs = { ')': '(', ']': '[', '}': '{' }\n  for (const ch of s) {\n    if (ch === '(' || ch === '[' || ch === '{') stack.push(ch)\n    else if (ch in pairs) {\n      if (stack.pop() === pairs[ch]) return false // BUG: comparison is inverted\n    }\n  }\n  return stack.length === 0\n}\nconsole.log(isBalanced(\"{[()()]}\"))",
      language: "javascript",
    },
    expected_output: { stdout: "true" },
    workstation_type: "coding",
    verification_type: "test_cases",
    verification_definition: { language: "javascript", testCases: [{ expectedStdout: "true" }] },
    points: 10,
    explanation: "The popped opening bracket should MATCH the expected pair for the string to still be valid — the buggy code returns false exactly when the brackets DO match. Changing `===` to `!==` fixes it: the function now returns false only on an actual mismatch.",
    tags: ["data-structures", "stacks", "debugging"],
  },
  {
    stream: "cse",
    competency_area: "Operating Systems",
    skill: "Deadlock Detection",
    challenge_type: "diagnosis",
    title: "Detect a Circular Wait in a Resource Allocation Graph",
    scenario: "Process P1 holds Resource R1 and is requesting R2. Process P2 holds Resource R2 and is requesting R1. No other processes or resources are involved in this system.",
    mission: "Determine whether this resource allocation state represents a deadlock.",
    learning_objective: "Recognize a circular-wait condition as the defining signature of deadlock in a resource allocation graph.",
    difficulty: "easy",
    estimated_minutes: 8,
    instructions: "Given P1 holds R1 and wants R2, while P2 holds R2 and wants R1, answer 'yes' or 'no': is the system deadlocked?",
    inputs: { allocation: "P1 holds R1 wants R2; P2 holds R2 wants R1" },
    expected_output: { answer: "yes" },
    workstation_type: "structured_response",
    verification_type: "rule_based",
    verification_definition: { rules: [{ field: "answer", equals: "yes" }] },
    points: 10,
    explanation: "P1→R2→P2→R1→P1 forms a cycle in the resource allocation graph with no way for either process to proceed or be preempted, satisfying all four Coffman conditions — this is a deadlock.",
    tags: ["operating-systems", "deadlock", "resource-allocation"],
  },

  // ─── ECE ──────────────────────────────────────────────────────────────

  // ─── EEE ──────────────────────────────────────────────────────────────

  // ─── Mechanical ─────────────────────────────────────────────────────────

  // ─── Civil ────────────────────────────────────────────────────────────

  // ─── MBA ──────────────────────────────────────────────────────────────

  // ─── AI/ML ────────────────────────────────────────────────────────────
  {
    stream: "ai-ml",
    competency_area: "Model Selection",
    skill: "Overfitting Diagnosis",
    challenge_type: "diagnosis",
    title: "Diagnose Overfitting From Train/Validation Accuracy",
    scenario: "A classification model achieves 98% accuracy on the training set but only 71% accuracy on the validation set, a gap that widened over the last several training epochs.",
    mission: "Identify the problem this train/validation gap indicates.",
    learning_objective: "Recognize the canonical accuracy-gap signature of overfitting, not underfitting or data leakage.",
    difficulty: "easy",
    estimated_minutes: 6,
    instructions: "Given a growing gap between high training accuracy (98%) and much lower validation accuracy (71%), select the diagnosis: 'overfitting', 'underfitting', 'data_leakage', or 'class_imbalance'.",
    inputs: { trainAccuracy: 0.98, valAccuracy: 0.71 },
    expected_output: { answer: "overfitting" },
    workstation_type: "structured_response",
    verification_type: "rule_based",
    verification_definition: { rules: [{ field: "answer", equals: "overfitting" }] },
    points: 10,
    explanation: "A large and widening gap between near-perfect training accuracy and much lower validation accuracy is the classic signature of overfitting — the model has memorized training-specific noise rather than learning generalizable patterns.",
    tags: ["machine-learning", "overfitting", "model-evaluation"],
  },
  {
    stream: "ai-ml",
    competency_area: "Data Preparation",
    skill: "Data Leakage Detection",
    challenge_type: "investigation",
    title: "Spot the Data Leakage in a Preprocessing Pipeline",
    scenario: "A data scientist's pipeline: (1) load the full dataset, (2) compute the mean and standard deviation for feature scaling using ALL the data, (3) split into train/test sets, (4) scale both sets using the mean/std from step 2, (5) train the model on the train set.",
    mission: "Identify which step introduces data leakage.",
    learning_objective: "Recognize that fitting a preprocessing transform on the full dataset before splitting leaks test-set information into training.",
    difficulty: "medium",
    estimated_minutes: 8,
    instructions: "Given the 5-step pipeline described, identify the step number (1-5) that introduces data leakage.",
    inputs: { pipelineSteps: 5 },
    expected_output: { answer: "2" },
    workstation_type: "structured_response",
    verification_type: "rule_based",
    verification_definition: { rules: [{ field: "answer", equals: "2" }] },
    points: 15,
    explanation: "Computing scaling statistics (mean/std) from the FULL dataset before the train/test split means test-set values influenced the transform applied to training data — the fit step must happen only on the training split, after splitting.",
    tags: ["machine-learning", "data-leakage", "preprocessing"],
  },
  {
    stream: "ai-ml",
    competency_area: "Model Evaluation",
    skill: "Metric Selection",
    challenge_type: "decision_making",
    title: "Choose the Right Evaluation Metric for a Highly Imbalanced Classifier",
    scenario: "A fraud detection model is trained on a dataset where only 1% of transactions are fraudulent. A naive model that always predicts 'not fraud' would score 99% accuracy while catching zero fraud cases.",
    mission: "Choose the metric family best suited to properly evaluate this model.",
    learning_objective: "Recognize why accuracy is misleading on imbalanced data and what to use instead.",
    difficulty: "easy",
    estimated_minutes: 6,
    instructions: "Given a 99%/1% class imbalance where accuracy is misleading, select the appropriate metric family: 'precision_recall_f1', 'accuracy', 'r_squared', or 'mean_absolute_error'.",
    inputs: { classBalance: "99% negative / 1% positive" },
    expected_output: { answer: "precision_recall_f1" },
    workstation_type: "structured_response",
    verification_type: "rule_based",
    verification_definition: { rules: [{ field: "answer", equals: "precision_recall_f1" }] },
    points: 10,
    explanation: "On heavily imbalanced data, accuracy rewards a model for ignoring the minority (positive) class entirely. Precision, recall, and F1 directly measure how well the model identifies the rare positive class, which is what actually matters for fraud detection.",
    tags: ["machine-learning", "model-evaluation", "imbalanced-data"],
  },
  {
    stream: "ai-ml",
    competency_area: "Feature Engineering",
    skill: "Feature Scaling",
    challenge_type: "decision_making",
    title: "Determine Whether Feature Scaling Is Required for a Distance-Based Model",
    scenario: "A K-Nearest-Neighbors model uses two features: annual income (ranging from 20,000 to 2,000,000) and age (ranging from 18 to 70). Without any preprocessing, distance calculations are almost entirely dominated by the income feature.",
    mission: "Decide whether feature scaling is required before training this model.",
    learning_objective: "Connect the mechanics of distance-based algorithms to the practical necessity of feature scaling.",
    difficulty: "easy",
    estimated_minutes: 6,
    instructions: "Given that KNN relies on distance calculations and one feature's range vastly dominates another's, answer 'yes' or 'no': is feature scaling required?",
    inputs: { model: "KNN", featureRanges: { income: [20000, 2000000], age: [18, 70] } },
    expected_output: { answer: "yes" },
    workstation_type: "structured_response",
    verification_type: "rule_based",
    verification_definition: { rules: [{ field: "answer", equals: "yes" }] },
    points: 10,
    explanation: "Distance-based models like KNN compute distances directly from raw feature values. Without scaling (e.g. standardization or min-max normalization), a feature with a much larger numeric range dominates the distance calculation, effectively making other features irrelevant to the model.",
    tags: ["machine-learning", "feature-engineering", "scaling"],
  },

  // ─── Data Science (ai-ds) ─────────────────────────────────────────────
  {
    stream: "ai-ds",
    competency_area: "Statistics",
    skill: "Central Tendency for Skewed Data",
    challenge_type: "data_interpretation",
    title: "Choose the Right Statistic for Skewed Income Data",
    scenario: "An analyst is summarizing household income for a city. The data is heavily right-skewed: most households earn Rs. 20,000-50,000/month, but a small number of outliers earn over Rs. 5,000,000/month, pulling the average far above what a typical household earns.",
    mission: "Choose the statistic that best represents the 'typical' household income given this skew.",
    learning_objective: "Recognize that the median, not the mean, is robust to outliers in skewed distributions.",
    difficulty: "easy",
    estimated_minutes: 6,
    instructions: "Given a right-skewed income distribution with extreme high-end outliers, select the best measure of 'typical' income: 'mean', 'median', 'mode', or 'standard_deviation'.",
    inputs: { distributionShape: "right-skewed with extreme outliers" },
    expected_output: { answer: "median" },
    workstation_type: "structured_response",
    verification_type: "rule_based",
    verification_definition: { rules: [{ field: "answer", equals: "median" }] },
    points: 10,
    explanation: "The mean is pulled toward extreme outliers in a skewed distribution; the median (the middle value) is robust to outliers and better represents a 'typical' household in this case.",
    tags: ["statistics", "eda", "central-tendency"],
  },
  {
    stream: "ai-ds",
    competency_area: "Data Cleaning",
    skill: "Missing Value Strategy",
    challenge_type: "decision_making",
    title: "Choose a Missing-Value Strategy for a Time-Ordered Sensor Reading",
    scenario: "A dataset of hourly temperature sensor readings has occasional single missing hours scattered throughout an otherwise continuous, smoothly-varying time series.",
    mission: "Choose the most appropriate way to fill these missing values.",
    learning_objective: "Match a missing-data strategy to the structure of the data (smooth time series) rather than applying a default blindly.",
    difficulty: "easy",
    estimated_minutes: 6,
    instructions: "Given scattered single missing hours in a smooth, continuous hourly temperature time series, select the best fill strategy: 'drop_rows', 'fill_with_zero', 'linear_interpolation', or 'fill_with_mode'.",
    inputs: { dataType: "continuous smooth hourly time series, scattered single missing points" },
    expected_output: { answer: "linear_interpolation" },
    workstation_type: "structured_response",
    verification_type: "rule_based",
    verification_definition: { rules: [{ field: "answer", equals: "linear_interpolation" }] },
    points: 10,
    explanation: "For a smoothly-varying time series with isolated missing points, linear interpolation between the neighboring known values is far more accurate than dropping rows, zero-filling, or using the mode — none of which respect the continuous trend.",
    tags: ["data-cleaning", "time-series", "missing-values"],
  },
  {
    stream: "ai-ds",
    competency_area: "Exploratory Data Analysis",
    skill: "Correlation Interpretation",
    challenge_type: "data_interpretation",
    title: "Identify the Correlation Type From a Scatter Plot Pattern",
    scenario: "A scatter plot of 'hours studied' (x-axis) versus 'exam score' (y-axis) for 200 students shows points trending clearly upward and to the right, with score consistently increasing as hours studied increases.",
    mission: "Identify the type of correlation shown by this scatter plot.",
    learning_objective: "Read a scatter plot's trend direction as the visual signature of correlation type.",
    difficulty: "easy",
    estimated_minutes: 6,
    instructions: "Given a scatter plot trending upward-right where both variables increase together, select: 'positive', 'negative', 'no_correlation', or 'nonlinear'.",
    inputs: { pattern: "upward trend, both variables increase together" },
    expected_output: { answer: "positive" },
    workstation_type: "structured_response",
    verification_type: "rule_based",
    verification_definition: { rules: [{ field: "answer", equals: "positive" }] },
    points: 10,
    explanation: "When both variables consistently increase together, forming an upward-right trend on a scatter plot, this indicates a positive correlation.",
    tags: ["data-science", "eda", "correlation"],
  },
  {
    stream: "ai-ds",
    competency_area: "Statistics",
    skill: "Experimental Design / Sampling Bias",
    challenge_type: "investigation",
    title: "Diagnose Sampling Bias in an A/B Test Design",
    scenario: "An e-commerce team runs an A/B test comparing two checkout page designs, but the experiment is only run on weekdays between 9 AM and 5 PM. The team then concludes design B is better and rolls it out to ALL traffic, including nights, weekends, and mobile users outside those hours.",
    mission: "Identify the flaw in this experiment's conclusion.",
    learning_objective: "Recognize sampling bias when a test's sample population doesn't match the population the conclusion gets applied to.",
    difficulty: "medium",
    estimated_minutes: 8,
    instructions: "Given the test ran only on a narrow time/day window but its result was applied to all traffic, select the flaw: 'sampling_bias', 'insufficient_sample_size', 'p_hacking', or 'confirmation_bias'.",
    inputs: { testWindow: "weekdays 9am-5pm only", appliedTo: "all traffic 24/7" },
    expected_output: { answer: "sampling_bias" },
    workstation_type: "structured_response",
    verification_type: "rule_based",
    verification_definition: { rules: [{ field: "answer", equals: "sampling_bias" }] },
    points: 15,
    explanation: "Running the experiment on a narrow, non-representative slice of traffic (weekday business hours only) and generalizing the result to the full, more diverse traffic population is a classic sampling bias — the tested sample does not represent the population the conclusion is applied to.",
    tags: ["data-science", "experimentation", "sampling-bias"],
  },

  // ─── Cybersecurity ────────────────────────────────────────────────────
  {
    stream: "cyber-security",
    competency_area: "Logs",
    skill: "Brute-Force Attack Detection",
    challenge_type: "investigation",
    title: "Investigate Suspicious Login Logs for a Brute-Force Pattern",
    scenario: "The login log for user 'admin' shows 47 failed login attempts from IP 203.0.113.9 within a 3-minute window, followed immediately by one successful login from the same IP.",
    mission: "Identify the type of attack this log pattern indicates.",
    learning_objective: "Recognize the high-frequency failed-then-successful-login signature of a brute-force/credential-stuffing attack.",
    difficulty: "easy",
    estimated_minutes: 8,
    instructions: "Given 47 failed logins in 3 minutes from one IP followed by a success from the same IP, select the attack type: 'brute_force', 'sql_injection', 'phishing', or 'dos'.",
    inputs: { failedAttempts: 47, windowMinutes: 3, outcome: "success after failures, same IP" },
    expected_output: { answer: "brute_force" },
    workstation_type: "log_investigation",
    verification_type: "rule_based",
    verification_definition: { rules: [{ field: "answer", equals: "brute_force" }] },
    points: 10,
    explanation: "A high volume of failed login attempts in a short window from a single source, followed by a success, is the textbook signature of a brute-force (or credential-stuffing) attack against the account.",
    tags: ["cybersecurity", "logs", "brute-force"],
  },
  {
    stream: "cyber-security",
    competency_area: "Secure Configuration",
    skill: "Vulnerable Configuration Identification",
    challenge_type: "diagnosis",
    title: "Identify the Vulnerable Setting in a Server Configuration",
    scenario: "A security review of a web server's configuration finds: TLS 1.2 enabled, admin panel exposed on the public internet with no IP allowlist, password minimum length of 12 characters, and automatic security patching enabled.",
    mission: "Identify which single setting is the most serious security vulnerability.",
    learning_objective: "Distinguish a genuinely exploitable misconfiguration from acceptable-baseline settings in the same list.",
    difficulty: "medium",
    estimated_minutes: 8,
    instructions: "Given TLS 1.2 enabled, admin panel publicly exposed with no IP allowlist, 12-character minimum passwords, and auto-patching enabled, select the setting that is the most serious vulnerability: 'tls_version', 'admin_panel_exposure', 'password_length', or 'auto_patching'.",
    inputs: { settings: ["tls_1.2", "admin_panel_public_no_allowlist", "password_min_12", "auto_patching_on"] },
    expected_output: { answer: "admin_panel_exposure" },
    workstation_type: "structured_response",
    verification_type: "rule_based",
    verification_definition: { rules: [{ field: "answer", equals: "admin_panel_exposure" }] },
    points: 15,
    explanation: "TLS 1.2, a 12-character password minimum, and auto-patching are all reasonable baseline practices. An admin panel exposed to the entire public internet with no IP allowlist is a directly exploitable attack surface — the clear standout risk.",
    tags: ["cybersecurity", "configuration", "attack-surface"],
  },
  {
    stream: "cyber-security",
    competency_area: "Incident Response",
    skill: "Incident Containment",
    challenge_type: "decision_making",
    title: "Choose the First Response Action During an Active Ransomware Incident",
    scenario: "A ransomware infection is actively spreading across file servers on the internal network. The security team has just confirmed the infection is real and ongoing.",
    mission: "Choose the correct first action to take.",
    learning_objective: "Apply the containment-first principle of incident response before any restoration or negotiation step.",
    difficulty: "medium",
    estimated_minutes: 8,
    instructions: "Given an actively spreading ransomware infection, select the first action: 'isolate_infected_hosts', 'restore_from_backup', 'pay_the_ransom', or 'wait_and_monitor'.",
    inputs: { situation: "active spreading ransomware infection" },
    expected_output: { answer: "isolate_infected_hosts" },
    workstation_type: "decision",
    verification_type: "rule_based",
    verification_definition: { rules: [{ field: "answer", equals: "isolate_infected_hosts" }] },
    points: 15,
    explanation: "The immediate priority during an active, spreading infection is containment — isolating infected hosts from the network to stop further spread — before any restoration, ransom-payment consideration, or further monitoring.",
    tags: ["cybersecurity", "incident-response", "containment"],
  },
  {
    stream: "cyber-security",
    competency_area: "Authorization",
    skill: "Privilege Escalation Detection",
    challenge_type: "diagnosis",
    title: "Diagnose an Access Control Vulnerability in a Web Application",
    scenario: "A web application includes a hidden form field `role=user` on account-settings requests. A tester changes this field to `role=admin` in the browser before submitting, and the server grants admin privileges without any additional server-side check.",
    mission: "Identify the vulnerability class this represents.",
    learning_objective: "Recognize that trusting client-supplied authorization data is a distinct, well-known vulnerability class.",
    difficulty: "easy",
    estimated_minutes: 8,
    instructions: "Given that client-supplied role data is trusted directly by the server with no server-side authorization check, select: 'privilege_escalation', 'sql_injection', 'cross_site_scripting', or 'denial_of_service'.",
    inputs: { behavior: "client-controlled role field trusted by server" },
    expected_output: { answer: "privilege_escalation" },
    workstation_type: "structured_response",
    verification_type: "rule_based",
    verification_definition: { rules: [{ field: "answer", equals: "privilege_escalation" }] },
    points: 10,
    explanation: "Trusting a client-supplied value to determine authorization level, with no independent server-side check, allows a user to escalate their own privileges — a classic privilege escalation / broken access control vulnerability.",
    tags: ["cybersecurity", "access-control", "privilege-escalation"],
  },

  // ─── IT ───────────────────────────────────────────────────────────────
  {
    stream: "it",
    competency_area: "Networking",
    skill: "DNS Troubleshooting",
    challenge_type: "diagnosis",
    title: "Diagnose a DNS Resolution Failure",
    scenario: "Users report they cannot reach 'app.company.com'. A ping to the server's raw IP address works fine, but `nslookup app.company.com` returns 'NXDOMAIN'.",
    mission: "Identify the most likely root cause of this failure.",
    learning_objective: "Distinguish a DNS-layer failure from a network-connectivity failure using the given symptoms.",
    difficulty: "easy",
    estimated_minutes: 8,
    instructions: "Given that pinging the raw IP succeeds but nslookup for the domain returns NXDOMAIN, select the most likely cause: 'dns_record_missing', 'network_cable_fault', 'firewall_blocking_icmp', or 'server_down'.",
    inputs: { pingIp: "succeeds", nslookupDomain: "NXDOMAIN" },
    expected_output: { answer: "dns_record_missing" },
    workstation_type: "log_investigation",
    verification_type: "rule_based",
    verification_definition: { rules: [{ field: "answer", equals: "dns_record_missing" }] },
    points: 10,
    explanation: "The server itself is reachable (ping by IP works), ruling out network/server-down causes — NXDOMAIN specifically means the DNS record for that name doesn't exist or isn't propagated, pointing directly at a missing/misconfigured DNS record.",
    tags: ["networking", "dns", "troubleshooting"],
  },
  {
    stream: "it",
    competency_area: "Cloud",
    skill: "Autoscaling Configuration Choice",
    challenge_type: "decision_making",
    title: "Choose the Right Cloud Scaling Strategy for a Traffic Spike Pattern",
    scenario: "An e-commerce site has predictable, sharp traffic spikes every day at 8 PM (a flash sale) but otherwise steady, low traffic. The current setup runs a fixed number of servers 24/7, which is both wasteful off-peak and occasionally overwhelmed at 8 PM.",
    mission: "Choose the most appropriate scaling strategy for this traffic pattern.",
    learning_objective: "Match a scaling strategy to a known, predictable load pattern rather than defaulting to always-on fixed capacity.",
    difficulty: "easy",
    estimated_minutes: 6,
    instructions: "Given a predictable daily spike at a fixed time and steady low traffic otherwise, select the strategy: 'scheduled_autoscaling', 'fixed_capacity', 'manual_scaling_only', or 'no_scaling_needed'.",
    inputs: { pattern: "predictable daily spike at fixed time" },
    expected_output: { answer: "scheduled_autoscaling" },
    workstation_type: "structured_response",
    verification_type: "rule_based",
    verification_definition: { rules: [{ field: "answer", equals: "scheduled_autoscaling" }] },
    points: 10,
    explanation: "Since the spike time is known and predictable, scheduled autoscaling (pre-scaling capacity up just before 8 PM and back down after) handles the load without the waste of fixed 24/7 capacity or the risk of reactive-only scaling lagging behind a sharp, sudden spike.",
    tags: ["cloud", "scaling", "infrastructure"],
  },
  {
    stream: "it",
    competency_area: "Systems Administration",
    skill: "Process Troubleshooting",
    challenge_type: "diagnosis",
    title: "Choose the Correct First Diagnostic Step for a Runaway Process",
    scenario: "A production server's load average has spiked sharply. Checking running processes shows one single process consistently using 98% CPU while every other process remains idle.",
    mission: "Choose the correct first diagnostic step.",
    learning_objective: "Prioritize investigation over disruptive action when a root cause is not yet understood.",
    difficulty: "easy",
    estimated_minutes: 6,
    instructions: "Given one process is pinning CPU at 98% while everything else is idle, select the first step: 'identify_and_investigate_the_process', 'reboot_immediately', 'ignore_it', or 'increase_swap_space'.",
    inputs: { symptom: "one process at 98% CPU, others idle" },
    expected_output: { answer: "identify_and_investigate_the_process" },
    workstation_type: "log_investigation",
    verification_type: "rule_based",
    verification_definition: { rules: [{ field: "answer", equals: "identify_and_investigate_the_process" }] },
    points: 10,
    explanation: "Before taking any disruptive action like rebooting, the correct first step is to identify what the runaway process is actually doing (via top/ps/strace/logs) — rebooting blindly loses the diagnostic opportunity and the issue may simply recur right after restart.",
    tags: ["it", "systems-administration", "troubleshooting"],
  },
  {
    stream: "it",
    competency_area: "Databases",
    skill: "Query Performance Diagnosis",
    challenge_type: "diagnosis",
    title: "Diagnose the Cause of a Slow Database Query",
    scenario: "A query filtering a 5-million-row `orders` table by `customer_email` takes 8 seconds to run. An equivalent query filtering by the primary key `order_id` on the same table returns instantly. `customer_email` has no index.",
    mission: "Identify the most likely cause of the slow query.",
    learning_objective: "Connect index absence on a large table to full-table-scan query performance symptoms.",
    difficulty: "easy",
    estimated_minutes: 8,
    instructions: "Given the slow query filters an unindexed column on a large table while the fast query uses the primary key, select the cause: 'missing_index', 'network_latency', 'insufficient_ram', or 'wrong_query_syntax'.",
    inputs: { tableRows: 5000000, slowColumn: "customer_email (no index)", fastColumn: "order_id (primary key)" },
    expected_output: { answer: "missing_index" },
    workstation_type: "structured_response",
    verification_type: "rule_based",
    verification_definition: { rules: [{ field: "answer", equals: "missing_index" }] },
    points: 10,
    explanation: "Without an index, the database must scan all 5 million rows (a full table scan) to find matches on customer_email, while the primary-key lookup uses its index for near-instant access — the fix is adding an index on customer_email.",
    tags: ["it", "databases", "query-performance"],
  },

  // ─── MCA ──────────────────────────────────────────────────────────────
  {
    stream: "mca",
    competency_area: "Programming",
    skill: "String Processing",
    challenge_type: "implementation",
    title: "Find the First Non-Repeating Character in a String",
    scenario: "A text-processing utility needs a function that identifies the first character in a string that does not repeat anywhere else in that string — a common building block for tokenizer and log-parsing utilities.",
    mission: "Implement a function that returns the first non-repeating character in a given string, or '_' if none exists, and print the result.",
    learning_objective: "Correctly implement a frequency-count-based string algorithm.",
    difficulty: "easy",
    estimated_minutes: 10,
    instructions: "Implement `firstNonRepeating(s)` for the input \"swiss\" and print its result on one line.",
    inputs: {
      starterCode: "function firstNonRepeating(s) {\n  // TODO: implement\n}\nconsole.log(firstNonRepeating(\"swiss\"))",
      language: "javascript",
    },
    expected_output: { stdout: "w" },
    workstation_type: "coding",
    verification_type: "test_cases",
    verification_definition: { language: "javascript", testCases: [{ expectedStdout: "w" }] },
    points: 10,
    explanation: "In \"swiss\": s appears 3 times, w appears once, i appears once — w is the first character (by position) that appears exactly once.",
    tags: ["programming", "strings", "frequency-count"],
  },
  {
    stream: "mca",
    competency_area: "Databases",
    skill: "SQL Aggregation",
    challenge_type: "data_interpretation",
    title: "Find Departments With Above-Average Headcount",
    scenario: "An HR system tracks employees per department. Management wants to know which departments are overstaffed relative to the company average.",
    mission: "Write a SQL query that returns department names with more employees than the average department headcount.",
    learning_objective: "Use a subquery/aggregate comparison — a step beyond a plain GROUP BY.",
    difficulty: "medium",
    estimated_minutes: 10,
    instructions: "Query the `employees` table (columns: id, name, department) to find departments whose employee count exceeds the average employee count per department across all departments.",
    inputs: {
      dataset: {
        tableName: "employees",
        columns: ["id", "name", "department"],
        rows: [[1, "A", "Engineering"], [2, "B", "Engineering"], [3, "C", "Engineering"], [4, "D", "Sales"], [5, "E", "Sales"], [6, "F", "HR"]],
      },
    },
    expected_output: { columns: ["department"], rows: [["Engineering"]] },
    workstation_type: "sql",
    verification_type: "sql_result",
    verification_definition: {
      dataset: { tableName: "employees", columns: ["id", "name", "department"], rows: [[1, "A", "Engineering"], [2, "B", "Engineering"], [3, "C", "Engineering"], [4, "D", "Sales"], [5, "E", "Sales"], [6, "F", "HR"]] },
      expectedResult: { columns: ["department"], rows: [["Engineering"]] },
      matchMode: "unordered_rows",
    },
    points: 15,
    explanation: "Average headcount per department = 6 employees / 3 departments = 2. Engineering has 3 (above average); Sales has 2 and HR has 1 (at or below average). Only Engineering qualifies.",
    tags: ["databases", "sql", "aggregation"],
  },
  {
    stream: "mca",
    competency_area: "Testing",
    skill: "Test Case Design",
    challenge_type: "investigation",
    title: "Identify the Missing Critical Test Case for a Division Function",
    scenario: "A function `divide(a, b)` returns `a / b`. The existing test suite covers: dividing two positive integers, dividing a positive by a negative number, and dividing two negative numbers. There is no test for the case where `b` is 0.",
    mission: "Identify which critical edge case is missing from the test suite.",
    learning_objective: "Recognize division-by-zero as the single most important missing edge case for any division function.",
    difficulty: "easy",
    estimated_minutes: 6,
    instructions: "Given the described test coverage, select the missing critical edge case: 'division_by_zero', 'negative_numbers', 'decimal_numbers', or 'large_numbers'.",
    inputs: { existingTests: ["positive/positive", "positive/negative", "negative/negative"] },
    expected_output: { answer: "division_by_zero" },
    workstation_type: "structured_response",
    verification_type: "rule_based",
    verification_definition: { rules: [{ field: "answer", equals: "division_by_zero" }] },
    points: 10,
    explanation: "Division by zero is undefined behavior (or produces Infinity/NaN depending on the language) and is the single most critical edge case for any division function — its absence from the test suite is a serious gap, more urgent than the other listed options which are already partially covered by the described tests.",
    tags: ["testing", "edge-cases", "test-design"],
  },
  {
    stream: "mca",
    competency_area: "APIs",
    skill: "REST API Design",
    challenge_type: "diagnosis",
    title: "Diagnose Incorrect HTTP Status Code Usage in an API",
    scenario: "A REST API's `GET /users/:id` endpoint returns HTTP status 200 with a JSON body `{ \"error\": \"User not found\" }` whenever the requested user does not exist, instead of a non-2xx status code.",
    mission: "Identify the correct HTTP status code this endpoint should return instead.",
    learning_objective: "Apply REST status-code conventions to a concrete API design flaw.",
    difficulty: "easy",
    estimated_minutes: 6,
    instructions: "For a GET request to a resource that does not exist, the correct convention is HTTP 404 Not Found. Submit '404' as the answer.",
    inputs: { currentBehavior: "returns 200 with error message body for missing resource" },
    expected_output: { answer: "404" },
    workstation_type: "structured_response",
    verification_type: "rule_based",
    verification_definition: { rules: [{ field: "answer", equals: "404" }] },
    points: 10,
    explanation: "Returning 200 OK for a missing resource breaks REST conventions and misleads clients (and caching/monitoring layers) into treating a failure as success. The correct status for 'resource does not exist' is 404 Not Found.",
    tags: ["apis", "rest", "http-status-codes"],
  },

  // ─── Simulation vertical slice: ECE Signal Lab ─────────────────────────
  {
    stream: "ece",
    competency_area: "Signals",
    skill: "Waveform Diagnosis",
    challenge_type: "diagnosis",
    title: "Diagnose the Distorted Sensor Waveform",
    scenario: "A vibration sensor's output was captured on a dual-channel scope alongside a clean reference signal of the same frequency for comparison.",
    mission: "Inspect both channels on the scope and determine what is wrong with the sensor's output.",
    learning_objective: "Recognize amplitude clipping in a captured waveform and identify amplitude as the affected signal parameter.",
    difficulty: "easy",
    estimated_minutes: 8,
    instructions: "Use the oscilloscope's timebase, averaging, and gain controls to inspect CH2 (sensor output) against CH1 (reference), then submit your diagnosis.",
    inputs: {
      responseFields: [
        { key: "diagnosis", label: "What is wrong with CH2?", type: "select", options: ["Amplitude clipping", "Random noise", "DC offset drift", "Signal dropout"] },
        { key: "cause", label: "Which signal parameter is responsible?", type: "select", options: ["Amplitude", "Frequency", "Phase", "Sampling rate"] },
      ],
    },
    expected_output: {},
    workstation_type: "structured_response",
    verification_type: "rule_based",
    simulation_type: "waveform_lab",
    verification_definition: {
      simulation: {
        sampleCount: 400, durationMs: 20, seed: 7,
        channel1: { label: "Reference (CH1)", frequencyHz: 500, amplitude: 1 },
        channel2: { label: "Sensor Output (CH2)", frequencyHz: 500, amplitude: 1, anomaly: { type: "amplitude_clipping", severity: 0.55 } },
      },
      rules: [
        { field: "diagnosis", equals: "Amplitude clipping" },
        { field: "cause", equals: "Amplitude" },
      ],
    },
    points: 15,
    explanation: "CH2's peaks are flattened at a fixed ceiling/floor relative to CH1's smooth, undistorted sine — the signature of amplitude clipping, caused by the sensor's output exceeding its usable amplitude range.",
    tags: ["ece", "signals", "waveform", "diagnosis", "oscilloscope"],
  },

  // ─── Simulation vertical slice: Mechanical Materials Lab ───────────────
  {
    stream: "mechanical",
    competency_area: "Materials",
    skill: "Compression Test Interpretation",
    challenge_type: "diagnosis",
    title: "Determine Whether the Specimen Passes Compression Spec",
    scenario: "A batch-acceptance compression test was run on a structural specimen and the stress-strain trace was captured for review against the acceptance spec.",
    mission: "Step through the recorded test, identify where yielding begins, and decide whether the specimen meets the acceptance spec.",
    learning_objective: "Read a stress-strain curve and classify specimen behavior against a yield-based acceptance threshold.",
    difficulty: "easy",
    estimated_minutes: 9,
    instructions: "Use the load control to step through the captured test up to full load, compare where the curve leaves its elastic slope against the spec threshold line, then submit your classification.",
    inputs: {
      acceptanceStrainPct: 1.0,
      responseFields: [
        { key: "diagnosis", label: "Does the specimen pass the acceptance spec?", type: "select", options: ["Passes — stays within elastic limit past spec load", "Fails — yields before spec load", "Fails — fractures before spec load"] },
      ],
    },
    expected_output: {},
    workstation_type: "structured_response",
    verification_type: "rule_based",
    simulation_type: "compression_lab",
    verification_definition: {
      simulation: {
        steps: 40, maxStrainPct: 3, elasticModulusMPa: 20000,
        yieldStrainPct: 0.6, ultimateStrainPct: 1.8, ultimateStressMPa: 145,
        specimenLabel: "Specimen C-14",
      },
      rules: [{ field: "diagnosis", equals: "Fails — yields before spec load" }],
    },
    points: 15,
    explanation: "The trace departs from its initial straight-line elastic slope at about 0.6% strain — before the 1.0% spec threshold — so the specimen yields before reaching the required load and fails acceptance.",
    tags: ["mechanical", "materials", "compression", "diagnosis", "stress-strain"],
  },

  // ─── Simulation vertical slice: EEE Electrical Circuit Lab ─────────────
  {
    stream: "eee",
    competency_area: "Circuit Analysis",
    skill: "Series RLC Resonance",
    challenge_type: "investigation",
    title: "Find the Resonance Condition on a Series RLC Test Bench",
    scenario: "A bench is wired as a series R-L-C circuit driven by a variable-frequency source, with a voltmeter and ammeter across the components.",
    mission: "Sweep the source frequency and find the operating condition where the circuit approaches resonance.",
    learning_objective: "Recognize the resonance condition in a series RLC circuit — current peaks and the circuit becomes purely resistive when inductive and capacitive reactance cancel.",
    difficulty: "medium",
    estimated_minutes: 10,
    instructions: "Use the frequency control to sweep the test bench and observe the current, impedance, and phase readouts, then submit your finding.",
    inputs: {
      responseFields: [
        { key: "resonanceFrequencyHz", label: "Resonance frequency", type: "number", unit: "Hz", step: "1" },
        { key: "behavior", label: "What happens to the current at that frequency?", type: "select", options: ["Current reaches its maximum value", "Current reaches its minimum value", "Voltage across R drops to zero", "Circuit becomes purely inductive"] },
        { key: "conclusion", label: "What can you conclude about the circuit at that frequency?", type: "select", options: ["The circuit is purely resistive at this frequency", "The circuit is purely capacitive at this frequency", "The circuit is purely inductive at this frequency", "No current flows at this frequency"] },
      ],
    },
    expected_output: {},
    workstation_type: "structured_response",
    verification_type: "rule_based",
    simulation_type: "rlc_lab",
    verification_definition: {
      simulation: {
        resistanceOhms: 20, inductanceH: 0.02, capacitanceF: 50e-6, sourceVoltageV: 12,
        freqMinHz: 50, freqMaxHz: 500, sweepSteps: 90,
      },
      rules: [
        { field: "resonanceFrequencyHz", numeric: { expected: 159.15, tolerance: 8 } },
        { field: "behavior", equals: "Current reaches its maximum value" },
        { field: "conclusion", equals: "The circuit is purely resistive at this frequency" },
      ],
    },
    points: 20,
    explanation: "At resonance, inductive reactance (2*pi*f*L) equals capacitive reactance (1/(2*pi*f*C)), so they cancel — impedance drops to just R, current peaks, and the circuit is purely resistive. For this bench (L=20mH, C=50µF), that occurs near f0 = 1/(2*pi*sqrt(LC)) ≈ 159 Hz.",
    tags: ["eee", "circuits", "rlc", "resonance", "investigation"],
  },

  // ─── Simulation vertical slice: Civil Structures Lab ───────────────────
  {
    stream: "civil",
    competency_area: "Structural Reasoning",
    skill: "Beam Deflection & Bending Stress",
    challenge_type: "diagnosis",
    title: "Classify a Simply-Supported Beam Under a Point Load",
    scenario: "A steel beam spans between two supports on a site and must carry a point load from an equipment pad without exceeding the structural spec.",
    mission: "Load the beam to its design condition, read the resulting bending stress and deflection, and classify whether the beam meets the acceptance spec.",
    learning_objective: "Apply simply-supported beam bending-stress and deflection formulas to classify structural adequacy against allowable limits.",
    difficulty: "medium",
    estimated_minutes: 10,
    instructions: "Use the load control to scale the beam up to its full design load, read the resulting bending stress and deflection off the bench, then submit your classification.",
    inputs: {
      responseFields: [
        { key: "maxBendingStressMPa", label: "Maximum bending stress", type: "number", unit: "MPa", step: "0.1" },
        { key: "maxDeflectionMm", label: "Maximum deflection", type: "number", unit: "mm", step: "0.01" },
        { key: "classification", label: "Does the beam meet the acceptance spec?", type: "select", options: [
          "Safe — within both stress and deflection limits",
          "Unsafe — bending stress exceeds allowable",
          "Unsafe — deflection exceeds allowable limit",
        ] },
      ],
    },
    expected_output: {},
    workstation_type: "structured_response",
    verification_type: "rule_based",
    simulation_type: "beam_lab",
    verification_definition: {
      simulation: {
        spanMm: 4000, loadN: 20000, loadPositionMm: 1500, modulusMPa: 200000,
        sectionWidthMm: 100, sectionHeightMm: 200,
        allowableStressMPa: 150, allowableDeflectionMm: 13.3,
      },
      rules: [
        { field: "maxBendingStressMPa", numeric: { expected: 28.125, tolerance: 1.5 } },
        { field: "maxDeflectionMm", numeric: { expected: 1.758, tolerance: 0.2 } },
        { field: "classification", equals: "Safe — within both stress and deflection limits" },
      ],
    },
    points: 20,
    explanation: "At full design load (20 kN at 1.5m on a 4m span), the reaction moment is 18.75 kN·m, giving a bending stress of about 28.1 MPa (well under the 150 MPa allowable) and a deflection of about 1.76 mm (well under the 13.3 mm limit) — the beam is safe under both criteria.",
    tags: ["civil", "structures", "beam", "deflection", "bending-stress"],
  },

  // ─── Simulation vertical slice: MBA Business Lab ───────────────────────
  {
    stream: "mba",
    competency_area: "Operations",
    skill: "Inventory Stock-Level Decision",
    challenge_type: "decision_making",
    title: "Set a Stock Level That Meets Target Service Level Within Budget",
    scenario: "A distribution center's weekly demand for a fast-moving SKU is uniformly distributed, and the operations team must set a stock level before the next replenishment cycle.",
    mission: "Adjust the stock level, observe the resulting service level and weekly cost, and choose a stock level that meets the required service target within the cost budget.",
    learning_objective: "Apply a newsvendor-style holding/stockout cost tradeoff to make an inventory stocking decision under demand uncertainty.",
    difficulty: "medium",
    estimated_minutes: 10,
    instructions: "Use the stock-level control to explore the cost/service-level tradeoff on the dashboard, then submit the stock level you would set and your assessment.",
    inputs: {
      responseFields: [
        { key: "stockLevelUnits", label: "Stock level you would set", type: "number", unit: "units", step: "1" },
        { key: "decision", label: "Assessment", type: "select", options: [
          "Meets target service level within cost budget",
          "Fails to meet target service level",
          "Exceeds the cost budget",
        ] },
      ],
    },
    expected_output: {},
    workstation_type: "structured_response",
    verification_type: "rule_based",
    simulation_type: "operations_lab",
    verification_definition: {
      simulation: {
        demandLowUnits: 800, demandHighUnits: 1200, unitHoldingCost: 2, unitStockoutCost: 8,
        targetServiceLevelPct: 90, maxWeeklyCostBudget: 900,
      },
      rules: [
        { field: "stockLevelUnits", numeric: { expected: 1160, tolerance: 40 } },
        { field: "decision", equals: "Meets target service level within cost budget" },
      ],
    },
    points: 20,
    explanation: "Reaching the 90% service-level target requires a stock level of about 1160 units (800 + 90% of the 400-unit demand range). At that level, expected weekly cost is about $340 — well within the $900 budget — so the decision meets the target service level within the cost budget.",
    tags: ["mba", "operations", "inventory", "newsvendor", "decision-making"],
  },
]
