/**
 * arenaSeedChallenges.data.mjs — curated initial challenge library (spec
 * §59, §18). Four genuinely discipline-specific challenges per stream (44
 * total across 11 streams) — quality over quantity. Every entry goes
 * through the SAME validateChallengeContent pipeline AI-generated content
 * does (see arenaSeedChallenges.mjs) before being persisted; nothing here
 * is special-cased or exempt from the semantic-stream/vocabulary check.
 *
 * The library is meant to grow via the AI generation fallback as real
 * weekly demand exceeds it (spec §41) — this seed only needs to be large
 * enough that most weeks don't have to lean on generation for every
 * student in every stream.
 */

export const SEED_CHALLENGES = [
  // ─── CSE ──────────────────────────────────────────────────────────────
  {
    stream: "cse",
    competency_area: "Algorithms",
    skill: "Binary Search",
    challenge_type: "debugging",
    title: "Fix the Off-By-One in a Binary Search",
    scenario: "A teammate's binary search on a sorted array of user IDs sometimes returns the wrong index or loops forever when the target is the last element. Code review found the bug is in the loop bounds and midpoint update.",
    mission: "Read the buggy implementation below, fix the off-by-one error, and print the found index (or -1) for the given target.",
    learning_objective: "Correctly reason about inclusive/exclusive loop bounds in binary search.",
    difficulty: "easy",
    estimated_minutes: 10,
    instructions: "The starter code is provided as `inputs.starterCode`. Fix it in place (you may rewrite the function body) so it correctly binary-searches `arr` for `target` and prints only the resulting index on one line. Do not change the function name or the final print statement's format.",
    inputs: {
      starterCode: "function binarySearch(arr, target) {\n  let lo = 0, hi = arr.length; // BUG: should be arr.length - 1\n  while (lo < hi) { // BUG: wrong comparison causes infinite loop / wrong bounds\n    const mid = Math.floor((lo + hi) / 2)\n    if (arr[mid] === target) return mid\n    if (arr[mid] < target) lo = mid + 1\n    else hi = mid\n  }\n  return -1\n}\nconst arr = [2, 5, 8, 12, 16, 23, 38, 45, 56, 72, 91]\nconsole.log(binarySearch(arr, 91))",
      language: "javascript",
    },
    expected_output: { stdout: "10" },
    workstation_type: "coding",
    verification_type: "test_cases",
    verification_definition: { language: "javascript", testCases: [{ expectedStdout: "10" }] },
    points: 10,
    explanation: "The last element (index 10, value 91) must be reachable — using `hi = arr.length - 1` and `lo <= hi` (or an equivalent correctly-bounded loop) fixes both the infinite loop and the missed last element.",
    tags: ["algorithms", "binary-search", "debugging"],
  },
  {
    stream: "cse",
    competency_area: "Databases",
    skill: "SQL Aggregation",
    challenge_type: "data_interpretation",
    title: "Find Customers With Duplicate Orders on the Same Day",
    scenario: "The orders team suspects a checkout bug is double-submitting orders — the same customer placing what looks like two identical orders within the same day. Before filing a bug, they need proof from the orders table.",
    mission: "Write a SQL query against the `orders` table that returns customer_id and order_date for any customer with more than one order placed on the same date.",
    learning_objective: "Use GROUP BY / HAVING to detect duplicate-pattern rows — a genuine database reasoning task, not a plain filter.",
    difficulty: "easy",
    estimated_minutes: 10,
    instructions: "Query the `orders` table (columns: id, customer_id, order_date, amount). Return customer_id and order_date for every (customer_id, order_date) pair that appears more than once.",
    inputs: {
      dataset: {
        tableName: "orders",
        columns: ["id", "customer_id", "order_date", "amount"],
        rows: [
          [1, "C1", "2026-01-01", 500], [2, "C1", "2026-01-01", 500], [3, "C2", "2026-01-01", 300],
          [4, "C3", "2026-01-02", 700], [5, "C3", "2026-01-03", 700], [6, "C4", "2026-01-02", 200], [7, "C4", "2026-01-02", 250],
        ],
      },
    },
    expected_output: { columns: ["customer_id", "order_date"], rows: [["C1", "2026-01-01"], ["C4", "2026-01-02"]] },
    workstation_type: "sql",
    verification_type: "sql_result",
    verification_definition: {
      dataset: { tableName: "orders", columns: ["id", "customer_id", "order_date", "amount"], rows: [[1, "C1", "2026-01-01", 500], [2, "C1", "2026-01-01", 500], [3, "C2", "2026-01-01", 300], [4, "C3", "2026-01-02", 700], [5, "C3", "2026-01-03", 700], [6, "C4", "2026-01-02", 200], [7, "C4", "2026-01-02", 250]] },
      expectedResult: { columns: ["customer_id", "order_date"], rows: [["C1", "2026-01-01"], ["C4", "2026-01-02"]] },
      matchMode: "unordered_rows",
    },
    points: 10,
    explanation: "GROUP BY customer_id, order_date HAVING COUNT(*) > 1 is the standard pattern for detecting duplicate-row conditions in a table — a real database-reasoning skill beyond a plain WHERE filter.",
    tags: ["databases", "sql", "group-by"],
  },
  {
    stream: "cse",
    competency_area: "Data Structures",
    skill: "Stack-Based Parsing",
    challenge_type: "debugging",
    title: "Fix an Inverted Comparison in a Balanced-Parentheses Checker",
    scenario: "A code-review tool's bracket-matching utility is supposed to check whether a string's brackets are balanced, but it's flagging valid, correctly-balanced code as broken. A teammate suspects the stack comparison logic is inverted.",
    mission: "Find and fix the inverted comparison so the function correctly reports whether the given string's brackets are balanced.",
    learning_objective: "Correctly implement stack-based matching logic and recognize an inverted boolean comparison as a subtle, common bug class.",
    difficulty: "easy",
    estimated_minutes: 10,
    instructions: "Fix the starter code so it correctly prints \"true\" or \"false\" for whether the brackets in the given string are balanced. Do not change the function name or the final print statement's format.",
    inputs: {
      starterCode: "function isBalanced(s) {\n  const stack = []\n  const pairs = { ')': '(', ']': '[', '}': '{' }\n  for (const ch of s) {\n    if (ch === '(' || ch === '[' || ch === '{') stack.push(ch)\n    else if (ch in pairs) {\n      if (stack.pop() === pairs[ch]) return false // BUG: comparison is inverted\n    }\n  }\n  return stack.length === 0\n}\nconsole.log(isBalanced(\"{[()()]}\"))",
      language: "javascript",
    },
    expected_output: { stdout: "true" },
    workstation_type: "coding",
    verification_type: "test_cases",
    verification_definition: { language: "javascript", testCases: [{ expectedStdout: "true" }] },
    points: 10,
    explanation: "The popped opening bracket should MATCH the expected pair for the string to still be valid — the buggy code returns false exactly when the brackets DO match. Changing `===` to `!==` fixes it: the function now returns false only on an actual mismatch.",
    tags: ["data-structures", "stacks", "debugging"],
  },
  {
    stream: "cse",
    competency_area: "Operating Systems",
    skill: "Deadlock Detection",
    challenge_type: "diagnosis",
    title: "Detect a Circular Wait in a Resource Allocation Graph",
    scenario: "Process P1 holds Resource R1 and is requesting R2. Process P2 holds Resource R2 and is requesting R1. No other processes or resources are involved in this system.",
    mission: "Determine whether this resource allocation state represents a deadlock.",
    learning_objective: "Recognize a circular-wait condition as the defining signature of deadlock in a resource allocation graph.",
    difficulty: "easy",
    estimated_minutes: 8,
    instructions: "Given P1 holds R1 and wants R2, while P2 holds R2 and wants R1, answer 'yes' or 'no': is the system deadlocked?",
    inputs: { allocation: "P1 holds R1 wants R2; P2 holds R2 wants R1" },
    expected_output: { answer: "yes" },
    workstation_type: "structured_response",
    verification_type: "rule_based",
    verification_definition: { rules: [{ field: "answer", equals: "yes" }] },
    points: 10,
    explanation: "P1→R2→P2→R1→P1 forms a cycle in the resource allocation graph with no way for either process to proceed or be preempted, satisfying all four Coffman conditions — this is a deadlock.",
    tags: ["operating-systems", "deadlock", "resource-allocation"],
  },

  // ─── ECE ──────────────────────────────────────────────────────────────
  {
    stream: "ece",
    competency_area: "Digital Electronics",
    skill: "Logic Gate Fault Diagnosis",
    challenge_type: "diagnosis",
    title: "Diagnose a Stuck-At Fault in a 2-Input AND Gate Circuit",
    scenario: "A digital logic board has two cascaded AND gates: Y = (A AND B) AND C. During testing, the output Y is always 0 regardless of A, B, C — except the truth table row A=1,B=1,C=1 also gives Y=0, which should be the ONE case where Y=1.",
    mission: "Given the observed truth table, identify which internal signal is stuck-at-0 and name it.",
    learning_objective: "Trace a combinational logic fault from truth-table symptoms to the specific stuck signal.",
    difficulty: "medium",
    estimated_minutes: 10,
    instructions: "The circuit is Y = (A AND B) AND C, with an internal node N = A AND B feeding the second gate (Y = N AND C). Given that Y is 0 for every input combination including A=1,B=1,C=1, identify which single signal is stuck-at-0: A, B, C, N, or Y.",
    inputs: { truthTableNote: "Y=0 for all 8 input rows, including A=1,B=1,C=1 where correct Y should be 1." },
    expected_output: { answer: "Y" },
    workstation_type: "structured_response",
    verification_type: "rule_based",
    verification_definition: { rules: [{ field: "answer", equals: "Y" }] },
    points: 15,
    explanation: "If N (A AND B) were stuck-at-0, Y would still be forced to 0 in the same way — but N stuck-at-0 is indistinguishable from Y stuck-at-0 from Y's truth table alone UNLESS N is separately observable; since only Y is observed and it is 0 for the one case where both A AND B are 1 and C is 1 (which would make N=1 and Y=N AND C=1 if only C-path were broken), and Y is 0 in EVERY row (even where the correct value is 0), the simplest fault consistent with 'output pin always reads 0' is the output signal Y itself stuck-at-0 at the pin/probe.",
    tags: ["digital-electronics", "logic-gates", "fault-diagnosis"],
  },
  {
    stream: "ece",
    competency_area: "Signals",
    skill: "Nyquist Sampling",
    challenge_type: "calculation",
    title: "Detect Aliasing in a Sampled Audio Signal",
    scenario: "An embedded audio system samples an analog signal at 8000 Hz. A test tone of 5000 Hz is fed into the ADC. The engineer needs to know what frequency will actually appear in the sampled digital signal due to aliasing.",
    mission: "Calculate the aliased frequency that will appear in the digital output, given a sampling rate of 8000 Hz and an input tone of 5000 Hz.",
    learning_objective: "Apply the Nyquist criterion to compute an aliased frequency, not just recite the theorem.",
    difficulty: "medium",
    estimated_minutes: 8,
    instructions: "Sampling rate fs = 8000 Hz, input frequency f = 5000 Hz. Since f exceeds the Nyquist frequency (fs/2 = 4000 Hz), it aliases to |f - fs| = |5000 - 8000| = 3000 Hz. Submit the aliased frequency in Hz.",
    inputs: { samplingRateHz: 8000, inputFrequencyHz: 5000 },
    expected_output: { value: 3000 },
    workstation_type: "calculation",
    verification_type: "numeric_tolerance",
    verification_definition: { expectedValue: 3000, tolerance: 0 },
    points: 10,
    explanation: "Aliased frequency = |f - fs| when f > fs/2: |5000 - 8000| = 3000 Hz.",
    tags: ["signals", "sampling", "nyquist", "aliasing"],
  },
  {
    stream: "ece",
    competency_area: "Microcontrollers",
    skill: "UART Configuration",
    challenge_type: "calculation",
    title: "Calculate the UART Baud Rate Register Value for a Microcontroller",
    scenario: "An embedded engineer is configuring UART communication on an AVR microcontroller running from a 16 MHz crystal, targeting a baud rate of 250,000 for a high-speed sensor link.",
    mission: "Calculate the UBRR (baud rate register) value needed to configure this baud rate.",
    learning_objective: "Apply the standard AVR UART baud rate formula to a real configuration value.",
    difficulty: "medium",
    estimated_minutes: 8,
    instructions: "UBRR = (F_CPU / (16 × BaudRate)) − 1. F_CPU = 16,000,000 Hz, BaudRate = 250,000. Submit the UBRR value.",
    inputs: { fCpuHz: 16000000, baudRate: 250000 },
    expected_output: { value: 3 },
    workstation_type: "calculation",
    verification_type: "numeric_tolerance",
    verification_definition: { expectedValue: 3, tolerance: 0 },
    points: 10,
    explanation: "UBRR = (16,000,000 / (16 × 250,000)) − 1 = (16,000,000 / 4,000,000) − 1 = 4 − 1 = 3.",
    tags: ["embedded-systems", "microcontrollers", "uart"],
  },
  {
    stream: "ece",
    competency_area: "Communication Systems",
    skill: "Amplitude Modulation Bandwidth",
    challenge_type: "calculation",
    title: "Calculate the Transmission Bandwidth for an AM Radio Signal",
    scenario: "A broadcast engineer is designing an AM transmitter carrying an audio signal with a maximum modulating frequency of 5 kHz.",
    mission: "Calculate the minimum transmission bandwidth required for this AM signal.",
    learning_objective: "Apply the standard AM bandwidth formula, understanding why both sidebands matter.",
    difficulty: "easy",
    estimated_minutes: 6,
    instructions: "For AM, transmission bandwidth = 2 × highest modulating frequency. Modulating frequency = 5 kHz. Submit bandwidth in kHz.",
    inputs: { modulatingFrequencyKHz: 5 },
    expected_output: { value: 10 },
    workstation_type: "calculation",
    verification_type: "numeric_tolerance",
    verification_definition: { expectedValue: 10, tolerance: 0 },
    points: 10,
    explanation: "AM bandwidth = 2 × fm = 2 × 5 kHz = 10 kHz, since AM produces both an upper and a lower sideband, each spaced fm away from the carrier.",
    tags: ["communication-systems", "amplitude-modulation", "bandwidth"],
  },

  // ─── EEE ──────────────────────────────────────────────────────────────
  {
    stream: "eee",
    competency_area: "Circuit Analysis",
    skill: "Series-Parallel Resistance",
    challenge_type: "calculation",
    title: "Compute Equivalent Resistance of a Mixed Circuit",
    scenario: "A technician needs the total resistance seen by a 12V supply feeding a circuit: a 10-ohm resistor in series with a parallel combination of a 20-ohm and a 30-ohm resistor.",
    mission: "Calculate the total equivalent resistance of the circuit in ohms.",
    learning_objective: "Combine series and parallel resistance formulas correctly in one circuit.",
    difficulty: "easy",
    estimated_minutes: 8,
    instructions: "Parallel combination of 20 ohm and 30 ohm: (20*30)/(20+30) = 12 ohm. Add the series 10 ohm resistor: 10 + 12 = 22 ohm. Submit the total equivalent resistance in ohms.",
    inputs: { seriesResistorOhm: 10, parallelResistorsOhm: [20, 30] },
    expected_output: { value: 22 },
    workstation_type: "calculation",
    verification_type: "numeric_tolerance",
    verification_definition: { expectedValue: 22, tolerance: 0.5 },
    points: 10,
    explanation: "R_parallel = (20*30)/(20+30) = 12 ohm; R_total = R_series + R_parallel = 10 + 12 = 22 ohm.",
    tags: ["circuits", "resistance", "series-parallel"],
  },
  {
    stream: "eee",
    competency_area: "Electrical Machines",
    skill: "Induction Motor Fault Diagnosis",
    challenge_type: "diagnosis",
    title: "Diagnose a Single-Phasing Induction Motor",
    scenario: "A 3-phase induction motor hums loudly but fails to start, and draws high current on the phases that ARE energized. A voltage check shows one of the three supply phases reads 0V at the motor terminals.",
    mission: "Identify the most likely fault causing this symptom.",
    learning_objective: "Connect a specific symptom pattern (hums, won't start, one phase dead) to its root electrical-machine fault.",
    difficulty: "medium",
    estimated_minutes: 8,
    instructions: "Given: motor hums but doesn't rotate, draws high current, and one of three supply phases measures 0V at the terminals. Select the fault: 'single_phasing', 'bearing_wear', 'overvoltage', or 'rotor_short'.",
    inputs: { symptom: "hums, no rotation, high current, one phase at 0V" },
    expected_output: { answer: "single_phasing" },
    workstation_type: "structured_response",
    verification_type: "rule_based",
    verification_definition: { rules: [{ field: "answer", equals: "single_phasing" }] },
    points: 15,
    explanation: "A missing supply phase (single-phasing) removes the rotating magnetic field needed to start the motor from standstill — it hums (residual field from the two live phases) and draws excess current on the remaining phases trying to compensate, exactly matching a 0V reading on the third phase.",
    tags: ["electrical-machines", "induction-motor", "fault-diagnosis"],
  },
  {
    stream: "eee",
    competency_area: "Power Systems",
    skill: "Power Factor Calculations",
    challenge_type: "calculation",
    title: "Calculate Real Power Delivered to a Single-Phase Load",
    scenario: "A single-phase industrial load draws 10 A at 230 V with a lagging power factor of 0.8.",
    mission: "Calculate the real power (in watts) delivered to the load.",
    learning_objective: "Apply P = VI·cos(θ) correctly, distinguishing real power from apparent power.",
    difficulty: "easy",
    estimated_minutes: 6,
    instructions: "P = V × I × power factor = 230 × 10 × 0.8. Submit P in watts.",
    inputs: { voltage: 230, current: 10, powerFactor: 0.8 },
    expected_output: { value: 1840 },
    workstation_type: "calculation",
    verification_type: "numeric_tolerance",
    verification_definition: { expectedValue: 1840, tolerance: 5 },
    points: 10,
    explanation: "Real power P = V × I × cos(θ) = 230 × 10 × 0.8 = 1840 W.",
    tags: ["power-systems", "power-factor", "real-power"],
  },
  {
    stream: "eee",
    competency_area: "Control Systems",
    skill: "Stability Analysis",
    challenge_type: "diagnosis",
    title: "Determine Stability of a System From Its Pole Locations",
    scenario: "A control engineer computes the poles of a closed-loop transfer function and finds them at s = -2, s = -3, and s = +1.",
    mission: "Determine whether the system is stable or unstable based on these pole locations.",
    learning_objective: "Apply the left-half-plane stability criterion rather than just checking 'most' poles.",
    difficulty: "medium",
    estimated_minutes: 8,
    instructions: "A linear system is stable only if ALL poles have negative real parts. Poles are at -2, -3, and +1. Answer 'stable' or 'unstable'.",
    inputs: { poles: [-2, -3, 1] },
    expected_output: { answer: "unstable" },
    workstation_type: "structured_response",
    verification_type: "rule_based",
    verification_definition: { rules: [{ field: "answer", equals: "unstable" }] },
    points: 10,
    explanation: "A system is stable only when every pole of its transfer function lies in the left half of the s-plane (negative real part). The pole at s = +1 has a positive real part, so the system is unstable regardless of the other two poles.",
    tags: ["control-systems", "stability", "pole-zero-analysis"],
  },

  // ─── Mechanical ─────────────────────────────────────────────────────────
  {
    stream: "mechanical",
    competency_area: "Materials",
    skill: "Fracture Mode Identification",
    challenge_type: "diagnosis",
    title: "Identify a Fatigue Fracture From Its Surface Pattern",
    scenario: "A steel shaft failed after 8 months of continuous operation under cyclic bending load. The fracture surface shows smooth, concentric 'beach mark' rings radiating from a surface origin point, with a small rough final-rupture zone.",
    mission: "Identify the fracture mode responsible for this failure.",
    learning_objective: "Recognize the classic beach-mark signature of fatigue failure versus brittle or ductile overload.",
    difficulty: "medium",
    estimated_minutes: 8,
    instructions: "Given a fracture surface with concentric beach marks radiating from a surface origin and a small final rupture zone, after 8 months of cyclic loading, select the fracture mode: 'fatigue', 'brittle_overload', 'ductile_overload', or 'corrosion'.",
    inputs: { symptom: "beach marks, surface origin, cyclic load, small rupture zone" },
    expected_output: { answer: "fatigue" },
    workstation_type: "structured_response",
    verification_type: "rule_based",
    verification_definition: { rules: [{ field: "answer", equals: "fatigue" }] },
    points: 15,
    explanation: "Beach marks (also called striations at the microscale) forming concentric rings from a surface-initiated crack under repeated cyclic loading, ending in a small rapid-fracture zone, is the textbook signature of fatigue failure.",
    tags: ["materials", "failure-analysis", "fatigue"],
  },
  {
    stream: "mechanical",
    competency_area: "Thermal Engineering",
    skill: "Conduction Heat Transfer",
    challenge_type: "calculation",
    title: "Calculate Heat Loss Through a Furnace Wall",
    scenario: "A furnace wall is made of a 0.2 m thick brick layer with thermal conductivity k = 1.2 W/(m*K). The inner surface is at 500 C and the outer surface is at 100 C, over a wall area of 5 sq. m.",
    mission: "Calculate the steady-state heat transfer rate through the wall in watts, using Fourier's law of conduction.",
    learning_objective: "Apply Q = kA(dT)/L correctly with the given units.",
    difficulty: "easy",
    estimated_minutes: 8,
    instructions: "Q = k * A * (T_hot - T_cold) / L = 1.2 * 5 * (500 - 100) / 0.2. Submit Q in watts.",
    inputs: { k: 1.2, areaM2: 5, tHotC: 500, tColdC: 100, thicknessM: 0.2 },
    expected_output: { value: 12000 },
    workstation_type: "calculation",
    verification_type: "numeric_tolerance",
    verification_definition: { expectedValue: 12000, tolerance: 50 },
    points: 10,
    explanation: "Q = kA(dT)/L = 1.2 * 5 * 400 / 0.2 = 12000 W.",
    tags: ["thermal", "heat-transfer", "conduction"],
  },
  {
    stream: "mechanical",
    competency_area: "Manufacturing",
    skill: "Process Selection",
    challenge_type: "decision_making",
    title: "Choose the Right Manufacturing Process for High-Volume Plastic Parts",
    scenario: "A company needs to produce 100,000 identical small plastic clips per month with tight dimensional tolerances and the lowest possible cost per unit.",
    mission: "Select the most appropriate manufacturing process for this production requirement.",
    learning_objective: "Match a manufacturing process to volume, material, and tolerance requirements rather than defaulting to one process.",
    difficulty: "easy",
    estimated_minutes: 8,
    instructions: "Given high volume (100,000/month), plastic material, tight tolerance, and low per-unit cost priority, choose: 'injection_molding', 'cnc_machining', '3d_printing', or 'sand_casting'.",
    inputs: { volume: 100000, material: "plastic", priority: "low unit cost, tight tolerance" },
    expected_output: { answer: "injection_molding" },
    workstation_type: "structured_response",
    verification_type: "rule_based",
    verification_definition: { rules: [{ field: "answer", equals: "injection_molding" }] },
    points: 10,
    explanation: "Injection molding has high tooling cost but very low marginal cost per part and excellent repeatability at high volumes — exactly matching a 100,000-unit/month plastic part run, unlike CNC machining (too slow/costly per part at this volume), 3D printing (too slow for this volume), or sand casting (poor tolerance, wrong material class).",
    tags: ["manufacturing", "process-selection", "injection-molding"],
  },
  {
    stream: "mechanical",
    competency_area: "Machine Design",
    skill: "Factor of Safety Calculation",
    challenge_type: "calculation",
    title: "Calculate the Factor of Safety for a Shaft Under Load",
    scenario: "A steel shaft with a yield strength of 250 MPa experiences a calculated working stress of 50 MPa under its rated load.",
    mission: "Calculate the factor of safety for this shaft design.",
    learning_objective: "Apply the factor-of-safety formula as a design-verification calculation, not just a definition to recall.",
    difficulty: "easy",
    estimated_minutes: 6,
    instructions: "Factor of Safety = Yield Strength / Working Stress = 250 / 50. Submit the factor of safety (unitless).",
    inputs: { yieldStrengthMPa: 250, workingStressMPa: 50 },
    expected_output: { value: 5 },
    workstation_type: "calculation",
    verification_type: "numeric_tolerance",
    verification_definition: { expectedValue: 5, tolerance: 0.1 },
    points: 10,
    explanation: "Factor of Safety = Yield Strength / Working Stress = 250 / 50 = 5 — the shaft can withstand 5 times its expected working stress before yielding.",
    tags: ["machine-design", "factor-of-safety", "shaft-design"],
  },

  // ─── Civil ────────────────────────────────────────────────────────────
  {
    stream: "civil",
    competency_area: "Structural Reasoning",
    skill: "Simply Supported Beam Reactions",
    challenge_type: "calculation",
    title: "Calculate Support Reactions for a Loaded Beam",
    scenario: "A simply supported beam of 6 m span carries a single point load of 12 kN at 2 m from the left support (support A). The right support is B.",
    mission: "Calculate the reaction force at support A in kN, using static equilibrium.",
    learning_objective: "Apply moment equilibrium to compute a support reaction — core statics for structural analysis.",
    difficulty: "medium",
    estimated_minutes: 10,
    instructions: "Taking moments about B: R_A * 6 = 12 * (6 - 2) = 48, so R_A = 48/6 = 8 kN. Submit R_A in kN.",
    inputs: { spanM: 6, loadKN: 12, loadDistanceFromA: 2 },
    expected_output: { value: 8 },
    workstation_type: "calculation",
    verification_type: "numeric_tolerance",
    verification_definition: { expectedValue: 8, tolerance: 0.2 },
    points: 15,
    explanation: "Sum of moments about B = 0: R_A * 6 - 12 * 4 = 0 => R_A = 48/6 = 8 kN.",
    tags: ["structural", "statics", "beam-reactions"],
  },
  {
    stream: "civil",
    competency_area: "Materials",
    skill: "Concrete Curing Defect Diagnosis",
    challenge_type: "diagnosis",
    title: "Diagnose Map Cracking in a Concrete Slab",
    scenario: "A newly poured concrete slab shows a fine, interconnected network of shallow cracks resembling a map or dried mud, appearing within the first few days after the finish was troweled on a hot, windy day with no curing compound applied.",
    mission: "Identify the most likely cause of this cracking pattern.",
    learning_objective: "Connect a specific site condition (hot/windy pour, no curing) and crack pattern to plastic shrinkage cracking.",
    difficulty: "easy",
    estimated_minutes: 8,
    instructions: "Given a fine map-like crack pattern appearing within days, on a hot windy day with no curing compound, select the cause: 'plastic_shrinkage', 'structural_overload', 'rebar_corrosion', or 'freeze_thaw'.",
    inputs: { symptom: "map cracking, hot windy pour, no curing compound, early age" },
    expected_output: { answer: "plastic_shrinkage" },
    workstation_type: "structured_response",
    verification_type: "rule_based",
    verification_definition: { rules: [{ field: "answer", equals: "plastic_shrinkage" }] },
    points: 10,
    explanation: "Rapid surface moisture loss (hot, windy conditions, no curing compound) before the concrete gains strength causes plastic shrinkage cracking — a fine, random map-like pattern appearing within the first days.",
    tags: ["materials", "concrete", "curing-defects"],
  },
  {
    stream: "civil",
    competency_area: "Surveying",
    skill: "Traverse Error Calculation",
    challenge_type: "calculation",
    title: "Calculate the Linear Closing Error of a Traverse Survey",
    scenario: "A closed traverse survey has a departure (east-west) closing error of 0.06 m and a latitude (north-south) closing error of 0.08 m.",
    mission: "Calculate the total linear closing error of the traverse.",
    learning_objective: "Apply the Pythagorean closing-error formula to real traverse survey data.",
    difficulty: "medium",
    estimated_minutes: 8,
    instructions: "Linear error of closure = sqrt(ΔE² + ΔN²) = sqrt(0.06² + 0.08²). Submit the result in meters.",
    inputs: { departureErrorM: 0.06, latitudeErrorM: 0.08 },
    expected_output: { value: 0.1 },
    workstation_type: "calculation",
    verification_type: "numeric_tolerance",
    verification_definition: { expectedValue: 0.1, tolerance: 0.005 },
    points: 10,
    explanation: "Linear closing error = √(0.06² + 0.08²) = √(0.0036 + 0.0064) = √0.01 = 0.1 m.",
    tags: ["surveying", "traverse", "closing-error"],
  },
  {
    stream: "civil",
    competency_area: "Transportation",
    skill: "Pavement Distress Diagnosis",
    challenge_type: "diagnosis",
    title: "Diagnose the Cause of Premature Rutting in an Asphalt Pavement",
    scenario: "A newly paved asphalt road develops deep ruts in the wheel paths of the truck lane within a few months of hot summer weather and heavy truck traffic. No cracking or potholes are present, only depressions concentrated in the wheel path.",
    mission: "Identify the most likely cause of this rutting.",
    learning_objective: "Connect a specific pavement distress pattern (wheel-path rutting, no cracking) to its root cause among several plausible-sounding options.",
    difficulty: "medium",
    estimated_minutes: 8,
    instructions: "Given wheel-path-only rutting, no cracking, hot weather, and heavy truck loading, select the cause: 'insufficient_mix_stiffness', 'poor_drainage', 'subgrade_settlement', or 'freeze_thaw_cracking'.",
    inputs: { symptom: "wheel-path rutting, no cracking, hot weather, heavy trucks" },
    expected_output: { answer: "insufficient_mix_stiffness" },
    workstation_type: "structured_response",
    verification_type: "rule_based",
    verification_definition: { rules: [{ field: "answer", equals: "insufficient_mix_stiffness" }] },
    points: 15,
    explanation: "Wheel-path-concentrated rutting with no cracking, worsened by heat and heavy truck loading, is the classic signature of plastic deformation from an asphalt mix too soft for the traffic and temperature — not a drainage, subgrade-settlement, or freeze-thaw issue, each of which produces a distinctly different distress pattern.",
    tags: ["transportation", "pavement", "rutting"],
  },

  // ─── MBA ──────────────────────────────────────────────────────────────
  {
    stream: "mba",
    competency_area: "Finance",
    skill: "Break-Even Analysis",
    challenge_type: "calculation",
    title: "Calculate the Break-Even Point for a New Product Line",
    scenario: "A company is launching a new product with fixed costs of Rs. 500,000 per month. Each unit sells for Rs. 250 and has a variable cost of Rs. 150.",
    mission: "Calculate the break-even point in units per month.",
    learning_objective: "Apply the break-even formula (Fixed Costs / Contribution Margin) to a realistic business scenario.",
    difficulty: "easy",
    estimated_minutes: 8,
    instructions: "Contribution margin per unit = 250 - 150 = 100. Break-even units = Fixed Costs / Contribution Margin = 500000 / 100 = 5000. Submit the break-even quantity in units.",
    inputs: { fixedCosts: 500000, pricePerUnit: 250, variableCostPerUnit: 150 },
    expected_output: { value: 5000 },
    workstation_type: "calculation",
    verification_type: "numeric_tolerance",
    verification_definition: { expectedValue: 5000, tolerance: 10 },
    points: 10,
    explanation: "Break-even units = Fixed Costs / (Price - Variable Cost) = 500000 / 100 = 5000 units.",
    tags: ["finance", "break-even", "unit-economics"],
  },
  {
    stream: "mba",
    competency_area: "Operations",
    skill: "Bottleneck Identification",
    challenge_type: "diagnosis",
    title: "Identify the Bottleneck in a 4-Stage Production Line",
    scenario: "A production line has 4 sequential stages. Stage 1 processes 100 units/hour, Stage 2 processes 60 units/hour, Stage 3 processes 90 units/hour, and Stage 4 processes 80 units/hour. The overall line is producing far below expectations.",
    mission: "Identify which stage is the bottleneck limiting the entire line's throughput.",
    learning_objective: "Apply the theory-of-constraints principle: overall throughput is capped by the slowest stage.",
    difficulty: "easy",
    estimated_minutes: 6,
    instructions: "Given per-stage throughputs of 100, 60, 90, and 80 units/hour for stages 1-4, identify the bottleneck stage number (1, 2, 3, or 4).",
    inputs: { stageThroughputs: [100, 60, 90, 80] },
    expected_output: { answer: "2" },
    workstation_type: "structured_response",
    verification_type: "rule_based",
    verification_definition: { rules: [{ field: "answer", equals: "2" }] },
    points: 10,
    explanation: "The line's overall throughput can never exceed its slowest stage's capacity. Stage 2 at 60 units/hour is the lowest, so it caps the entire line at 60 units/hour regardless of the other stages' higher capacity.",
    tags: ["operations", "bottleneck", "throughput"],
  },
  {
    stream: "mba",
    competency_area: "Marketing",
    skill: "Customer Lifetime Value",
    challenge_type: "calculation",
    title: "Calculate Customer Lifetime Value for a Subscription Business",
    scenario: "A subscription retailer's average customer makes purchases worth Rs. 500 on average, 4 times per year, and remains a customer for an average of 5 years.",
    mission: "Calculate the customer lifetime value (CLV).",
    learning_objective: "Apply the CLV formula to a realistic subscription-business scenario.",
    difficulty: "easy",
    estimated_minutes: 6,
    instructions: "CLV = Average Purchase Value × Purchase Frequency per Year × Customer Lifespan in Years = 500 × 4 × 5. Submit CLV in rupees.",
    inputs: { avgPurchaseValue: 500, purchaseFrequencyPerYear: 4, lifespanYears: 5 },
    expected_output: { value: 10000 },
    workstation_type: "calculation",
    verification_type: "numeric_tolerance",
    verification_definition: { expectedValue: 10000, tolerance: 50 },
    points: 10,
    explanation: "CLV = 500 × 4 × 5 = Rs. 10,000 — the total revenue expected from an average customer over their relationship with the business.",
    tags: ["marketing", "customer-lifetime-value", "business-analytics"],
  },
  {
    stream: "mba",
    competency_area: "HR",
    skill: "Turnover Root-Cause Analysis",
    challenge_type: "diagnosis",
    title: "Diagnose the Root Cause of High Early-Tenure Turnover",
    scenario: "Exit interview data shows turnover is concentrated among high-performing employees who leave within their first 12 months. The most frequently cited reason is 'no clear path to promotion or skill growth,' even though pay is at or above market rate and manager satisfaction scores are high.",
    mission: "Identify the primary root cause category driving this turnover pattern.",
    learning_objective: "Distinguish the actual root cause from plausible-but-ruled-out alternatives using the given evidence.",
    difficulty: "medium",
    estimated_minutes: 8,
    instructions: "Given that pay and management satisfaction are already fine but employees cite 'no clear growth path,' select the root cause: 'career_growth', 'compensation', 'management_style', or 'work_life_balance'.",
    inputs: { exitReason: "no clear growth path", payCompetitive: true, managerSatisfaction: "high" },
    expected_output: { answer: "career_growth" },
    workstation_type: "structured_response",
    verification_type: "rule_based",
    verification_definition: { rules: [{ field: "answer", equals: "career_growth" }] },
    points: 10,
    explanation: "Since compensation and management satisfaction are already ruled out by the data, and the stated exit reason is explicitly about growth and promotion, the root cause is a lack of career growth opportunity, not pay or management style.",
    tags: ["hr", "turnover", "retention"],
  },

  // ─── AI/ML ────────────────────────────────────────────────────────────
  {
    stream: "ai-ml",
    competency_area: "Model Selection",
    skill: "Overfitting Diagnosis",
    challenge_type: "diagnosis",
    title: "Diagnose Overfitting From Train/Validation Accuracy",
    scenario: "A classification model achieves 98% accuracy on the training set but only 71% accuracy on the validation set, a gap that widened over the last several training epochs.",
    mission: "Identify the problem this train/validation gap indicates.",
    learning_objective: "Recognize the canonical accuracy-gap signature of overfitting, not underfitting or data leakage.",
    difficulty: "easy",
    estimated_minutes: 6,
    instructions: "Given a growing gap between high training accuracy (98%) and much lower validation accuracy (71%), select the diagnosis: 'overfitting', 'underfitting', 'data_leakage', or 'class_imbalance'.",
    inputs: { trainAccuracy: 0.98, valAccuracy: 0.71 },
    expected_output: { answer: "overfitting" },
    workstation_type: "structured_response",
    verification_type: "rule_based",
    verification_definition: { rules: [{ field: "answer", equals: "overfitting" }] },
    points: 10,
    explanation: "A large and widening gap between near-perfect training accuracy and much lower validation accuracy is the classic signature of overfitting — the model has memorized training-specific noise rather than learning generalizable patterns.",
    tags: ["machine-learning", "overfitting", "model-evaluation"],
  },
  {
    stream: "ai-ml",
    competency_area: "Data Preparation",
    skill: "Data Leakage Detection",
    challenge_type: "investigation",
    title: "Spot the Data Leakage in a Preprocessing Pipeline",
    scenario: "A data scientist's pipeline: (1) load the full dataset, (2) compute the mean and standard deviation for feature scaling using ALL the data, (3) split into train/test sets, (4) scale both sets using the mean/std from step 2, (5) train the model on the train set.",
    mission: "Identify which step introduces data leakage.",
    learning_objective: "Recognize that fitting a preprocessing transform on the full dataset before splitting leaks test-set information into training.",
    difficulty: "medium",
    estimated_minutes: 8,
    instructions: "Given the 5-step pipeline described, identify the step number (1-5) that introduces data leakage.",
    inputs: { pipelineSteps: 5 },
    expected_output: { answer: "2" },
    workstation_type: "structured_response",
    verification_type: "rule_based",
    verification_definition: { rules: [{ field: "answer", equals: "2" }] },
    points: 15,
    explanation: "Computing scaling statistics (mean/std) from the FULL dataset before the train/test split means test-set values influenced the transform applied to training data — the fit step must happen only on the training split, after splitting.",
    tags: ["machine-learning", "data-leakage", "preprocessing"],
  },
  {
    stream: "ai-ml",
    competency_area: "Model Evaluation",
    skill: "Metric Selection",
    challenge_type: "decision_making",
    title: "Choose the Right Evaluation Metric for a Highly Imbalanced Classifier",
    scenario: "A fraud detection model is trained on a dataset where only 1% of transactions are fraudulent. A naive model that always predicts 'not fraud' would score 99% accuracy while catching zero fraud cases.",
    mission: "Choose the metric family best suited to properly evaluate this model.",
    learning_objective: "Recognize why accuracy is misleading on imbalanced data and what to use instead.",
    difficulty: "easy",
    estimated_minutes: 6,
    instructions: "Given a 99%/1% class imbalance where accuracy is misleading, select the appropriate metric family: 'precision_recall_f1', 'accuracy', 'r_squared', or 'mean_absolute_error'.",
    inputs: { classBalance: "99% negative / 1% positive" },
    expected_output: { answer: "precision_recall_f1" },
    workstation_type: "structured_response",
    verification_type: "rule_based",
    verification_definition: { rules: [{ field: "answer", equals: "precision_recall_f1" }] },
    points: 10,
    explanation: "On heavily imbalanced data, accuracy rewards a model for ignoring the minority (positive) class entirely. Precision, recall, and F1 directly measure how well the model identifies the rare positive class, which is what actually matters for fraud detection.",
    tags: ["machine-learning", "model-evaluation", "imbalanced-data"],
  },
  {
    stream: "ai-ml",
    competency_area: "Feature Engineering",
    skill: "Feature Scaling",
    challenge_type: "decision_making",
    title: "Determine Whether Feature Scaling Is Required for a Distance-Based Model",
    scenario: "A K-Nearest-Neighbors model uses two features: annual income (ranging from 20,000 to 2,000,000) and age (ranging from 18 to 70). Without any preprocessing, distance calculations are almost entirely dominated by the income feature.",
    mission: "Decide whether feature scaling is required before training this model.",
    learning_objective: "Connect the mechanics of distance-based algorithms to the practical necessity of feature scaling.",
    difficulty: "easy",
    estimated_minutes: 6,
    instructions: "Given that KNN relies on distance calculations and one feature's range vastly dominates another's, answer 'yes' or 'no': is feature scaling required?",
    inputs: { model: "KNN", featureRanges: { income: [20000, 2000000], age: [18, 70] } },
    expected_output: { answer: "yes" },
    workstation_type: "structured_response",
    verification_type: "rule_based",
    verification_definition: { rules: [{ field: "answer", equals: "yes" }] },
    points: 10,
    explanation: "Distance-based models like KNN compute distances directly from raw feature values. Without scaling (e.g. standardization or min-max normalization), a feature with a much larger numeric range dominates the distance calculation, effectively making other features irrelevant to the model.",
    tags: ["machine-learning", "feature-engineering", "scaling"],
  },

  // ─── Data Science (ai-ds) ─────────────────────────────────────────────
  {
    stream: "ai-ds",
    competency_area: "Statistics",
    skill: "Central Tendency for Skewed Data",
    challenge_type: "data_interpretation",
    title: "Choose the Right Statistic for Skewed Income Data",
    scenario: "An analyst is summarizing household income for a city. The data is heavily right-skewed: most households earn Rs. 20,000-50,000/month, but a small number of outliers earn over Rs. 5,000,000/month, pulling the average far above what a typical household earns.",
    mission: "Choose the statistic that best represents the 'typical' household income given this skew.",
    learning_objective: "Recognize that the median, not the mean, is robust to outliers in skewed distributions.",
    difficulty: "easy",
    estimated_minutes: 6,
    instructions: "Given a right-skewed income distribution with extreme high-end outliers, select the best measure of 'typical' income: 'mean', 'median', 'mode', or 'standard_deviation'.",
    inputs: { distributionShape: "right-skewed with extreme outliers" },
    expected_output: { answer: "median" },
    workstation_type: "structured_response",
    verification_type: "rule_based",
    verification_definition: { rules: [{ field: "answer", equals: "median" }] },
    points: 10,
    explanation: "The mean is pulled toward extreme outliers in a skewed distribution; the median (the middle value) is robust to outliers and better represents a 'typical' household in this case.",
    tags: ["statistics", "eda", "central-tendency"],
  },
  {
    stream: "ai-ds",
    competency_area: "Data Cleaning",
    skill: "Missing Value Strategy",
    challenge_type: "decision_making",
    title: "Choose a Missing-Value Strategy for a Time-Ordered Sensor Reading",
    scenario: "A dataset of hourly temperature sensor readings has occasional single missing hours scattered throughout an otherwise continuous, smoothly-varying time series.",
    mission: "Choose the most appropriate way to fill these missing values.",
    learning_objective: "Match a missing-data strategy to the structure of the data (smooth time series) rather than applying a default blindly.",
    difficulty: "easy",
    estimated_minutes: 6,
    instructions: "Given scattered single missing hours in a smooth, continuous hourly temperature time series, select the best fill strategy: 'drop_rows', 'fill_with_zero', 'linear_interpolation', or 'fill_with_mode'.",
    inputs: { dataType: "continuous smooth hourly time series, scattered single missing points" },
    expected_output: { answer: "linear_interpolation" },
    workstation_type: "structured_response",
    verification_type: "rule_based",
    verification_definition: { rules: [{ field: "answer", equals: "linear_interpolation" }] },
    points: 10,
    explanation: "For a smoothly-varying time series with isolated missing points, linear interpolation between the neighboring known values is far more accurate than dropping rows, zero-filling, or using the mode — none of which respect the continuous trend.",
    tags: ["data-cleaning", "time-series", "missing-values"],
  },
  {
    stream: "ai-ds",
    competency_area: "Exploratory Data Analysis",
    skill: "Correlation Interpretation",
    challenge_type: "data_interpretation",
    title: "Identify the Correlation Type From a Scatter Plot Pattern",
    scenario: "A scatter plot of 'hours studied' (x-axis) versus 'exam score' (y-axis) for 200 students shows points trending clearly upward and to the right, with score consistently increasing as hours studied increases.",
    mission: "Identify the type of correlation shown by this scatter plot.",
    learning_objective: "Read a scatter plot's trend direction as the visual signature of correlation type.",
    difficulty: "easy",
    estimated_minutes: 6,
    instructions: "Given a scatter plot trending upward-right where both variables increase together, select: 'positive', 'negative', 'no_correlation', or 'nonlinear'.",
    inputs: { pattern: "upward trend, both variables increase together" },
    expected_output: { answer: "positive" },
    workstation_type: "structured_response",
    verification_type: "rule_based",
    verification_definition: { rules: [{ field: "answer", equals: "positive" }] },
    points: 10,
    explanation: "When both variables consistently increase together, forming an upward-right trend on a scatter plot, this indicates a positive correlation.",
    tags: ["data-science", "eda", "correlation"],
  },
  {
    stream: "ai-ds",
    competency_area: "Statistics",
    skill: "Experimental Design / Sampling Bias",
    challenge_type: "investigation",
    title: "Diagnose Sampling Bias in an A/B Test Design",
    scenario: "An e-commerce team runs an A/B test comparing two checkout page designs, but the experiment is only run on weekdays between 9 AM and 5 PM. The team then concludes design B is better and rolls it out to ALL traffic, including nights, weekends, and mobile users outside those hours.",
    mission: "Identify the flaw in this experiment's conclusion.",
    learning_objective: "Recognize sampling bias when a test's sample population doesn't match the population the conclusion gets applied to.",
    difficulty: "medium",
    estimated_minutes: 8,
    instructions: "Given the test ran only on a narrow time/day window but its result was applied to all traffic, select the flaw: 'sampling_bias', 'insufficient_sample_size', 'p_hacking', or 'confirmation_bias'.",
    inputs: { testWindow: "weekdays 9am-5pm only", appliedTo: "all traffic 24/7" },
    expected_output: { answer: "sampling_bias" },
    workstation_type: "structured_response",
    verification_type: "rule_based",
    verification_definition: { rules: [{ field: "answer", equals: "sampling_bias" }] },
    points: 15,
    explanation: "Running the experiment on a narrow, non-representative slice of traffic (weekday business hours only) and generalizing the result to the full, more diverse traffic population is a classic sampling bias — the tested sample does not represent the population the conclusion is applied to.",
    tags: ["data-science", "experimentation", "sampling-bias"],
  },

  // ─── Cybersecurity ────────────────────────────────────────────────────
  {
    stream: "cyber-security",
    competency_area: "Logs",
    skill: "Brute-Force Attack Detection",
    challenge_type: "investigation",
    title: "Investigate Suspicious Login Logs for a Brute-Force Pattern",
    scenario: "The login log for user 'admin' shows 47 failed login attempts from IP 203.0.113.9 within a 3-minute window, followed immediately by one successful login from the same IP.",
    mission: "Identify the type of attack this log pattern indicates.",
    learning_objective: "Recognize the high-frequency failed-then-successful-login signature of a brute-force/credential-stuffing attack.",
    difficulty: "easy",
    estimated_minutes: 8,
    instructions: "Given 47 failed logins in 3 minutes from one IP followed by a success from the same IP, select the attack type: 'brute_force', 'sql_injection', 'phishing', or 'dos'.",
    inputs: { failedAttempts: 47, windowMinutes: 3, outcome: "success after failures, same IP" },
    expected_output: { answer: "brute_force" },
    workstation_type: "log_investigation",
    verification_type: "rule_based",
    verification_definition: { rules: [{ field: "answer", equals: "brute_force" }] },
    points: 10,
    explanation: "A high volume of failed login attempts in a short window from a single source, followed by a success, is the textbook signature of a brute-force (or credential-stuffing) attack against the account.",
    tags: ["cybersecurity", "logs", "brute-force"],
  },
  {
    stream: "cyber-security",
    competency_area: "Secure Configuration",
    skill: "Vulnerable Configuration Identification",
    challenge_type: "diagnosis",
    title: "Identify the Vulnerable Setting in a Server Configuration",
    scenario: "A security review of a web server's configuration finds: TLS 1.2 enabled, admin panel exposed on the public internet with no IP allowlist, password minimum length of 12 characters, and automatic security patching enabled.",
    mission: "Identify which single setting is the most serious security vulnerability.",
    learning_objective: "Distinguish a genuinely exploitable misconfiguration from acceptable-baseline settings in the same list.",
    difficulty: "medium",
    estimated_minutes: 8,
    instructions: "Given TLS 1.2 enabled, admin panel publicly exposed with no IP allowlist, 12-character minimum passwords, and auto-patching enabled, select the setting that is the most serious vulnerability: 'tls_version', 'admin_panel_exposure', 'password_length', or 'auto_patching'.",
    inputs: { settings: ["tls_1.2", "admin_panel_public_no_allowlist", "password_min_12", "auto_patching_on"] },
    expected_output: { answer: "admin_panel_exposure" },
    workstation_type: "structured_response",
    verification_type: "rule_based",
    verification_definition: { rules: [{ field: "answer", equals: "admin_panel_exposure" }] },
    points: 15,
    explanation: "TLS 1.2, a 12-character password minimum, and auto-patching are all reasonable baseline practices. An admin panel exposed to the entire public internet with no IP allowlist is a directly exploitable attack surface — the clear standout risk.",
    tags: ["cybersecurity", "configuration", "attack-surface"],
  },
  {
    stream: "cyber-security",
    competency_area: "Incident Response",
    skill: "Incident Containment",
    challenge_type: "decision_making",
    title: "Choose the First Response Action During an Active Ransomware Incident",
    scenario: "A ransomware infection is actively spreading across file servers on the internal network. The security team has just confirmed the infection is real and ongoing.",
    mission: "Choose the correct first action to take.",
    learning_objective: "Apply the containment-first principle of incident response before any restoration or negotiation step.",
    difficulty: "medium",
    estimated_minutes: 8,
    instructions: "Given an actively spreading ransomware infection, select the first action: 'isolate_infected_hosts', 'restore_from_backup', 'pay_the_ransom', or 'wait_and_monitor'.",
    inputs: { situation: "active spreading ransomware infection" },
    expected_output: { answer: "isolate_infected_hosts" },
    workstation_type: "decision",
    verification_type: "rule_based",
    verification_definition: { rules: [{ field: "answer", equals: "isolate_infected_hosts" }] },
    points: 15,
    explanation: "The immediate priority during an active, spreading infection is containment — isolating infected hosts from the network to stop further spread — before any restoration, ransom-payment consideration, or further monitoring.",
    tags: ["cybersecurity", "incident-response", "containment"],
  },
  {
    stream: "cyber-security",
    competency_area: "Authorization",
    skill: "Privilege Escalation Detection",
    challenge_type: "diagnosis",
    title: "Diagnose an Access Control Vulnerability in a Web Application",
    scenario: "A web application includes a hidden form field `role=user` on account-settings requests. A tester changes this field to `role=admin` in the browser before submitting, and the server grants admin privileges without any additional server-side check.",
    mission: "Identify the vulnerability class this represents.",
    learning_objective: "Recognize that trusting client-supplied authorization data is a distinct, well-known vulnerability class.",
    difficulty: "easy",
    estimated_minutes: 8,
    instructions: "Given that client-supplied role data is trusted directly by the server with no server-side authorization check, select: 'privilege_escalation', 'sql_injection', 'cross_site_scripting', or 'denial_of_service'.",
    inputs: { behavior: "client-controlled role field trusted by server" },
    expected_output: { answer: "privilege_escalation" },
    workstation_type: "structured_response",
    verification_type: "rule_based",
    verification_definition: { rules: [{ field: "answer", equals: "privilege_escalation" }] },
    points: 10,
    explanation: "Trusting a client-supplied value to determine authorization level, with no independent server-side check, allows a user to escalate their own privileges — a classic privilege escalation / broken access control vulnerability.",
    tags: ["cybersecurity", "access-control", "privilege-escalation"],
  },

  // ─── IT ───────────────────────────────────────────────────────────────
  {
    stream: "it",
    competency_area: "Networking",
    skill: "DNS Troubleshooting",
    challenge_type: "diagnosis",
    title: "Diagnose a DNS Resolution Failure",
    scenario: "Users report they cannot reach 'app.company.com'. A ping to the server's raw IP address works fine, but `nslookup app.company.com` returns 'NXDOMAIN'.",
    mission: "Identify the most likely root cause of this failure.",
    learning_objective: "Distinguish a DNS-layer failure from a network-connectivity failure using the given symptoms.",
    difficulty: "easy",
    estimated_minutes: 8,
    instructions: "Given that pinging the raw IP succeeds but nslookup for the domain returns NXDOMAIN, select the most likely cause: 'dns_record_missing', 'network_cable_fault', 'firewall_blocking_icmp', or 'server_down'.",
    inputs: { pingIp: "succeeds", nslookupDomain: "NXDOMAIN" },
    expected_output: { answer: "dns_record_missing" },
    workstation_type: "log_investigation",
    verification_type: "rule_based",
    verification_definition: { rules: [{ field: "answer", equals: "dns_record_missing" }] },
    points: 10,
    explanation: "The server itself is reachable (ping by IP works), ruling out network/server-down causes — NXDOMAIN specifically means the DNS record for that name doesn't exist or isn't propagated, pointing directly at a missing/misconfigured DNS record.",
    tags: ["networking", "dns", "troubleshooting"],
  },
  {
    stream: "it",
    competency_area: "Cloud",
    skill: "Autoscaling Configuration Choice",
    challenge_type: "decision_making",
    title: "Choose the Right Cloud Scaling Strategy for a Traffic Spike Pattern",
    scenario: "An e-commerce site has predictable, sharp traffic spikes every day at 8 PM (a flash sale) but otherwise steady, low traffic. The current setup runs a fixed number of servers 24/7, which is both wasteful off-peak and occasionally overwhelmed at 8 PM.",
    mission: "Choose the most appropriate scaling strategy for this traffic pattern.",
    learning_objective: "Match a scaling strategy to a known, predictable load pattern rather than defaulting to always-on fixed capacity.",
    difficulty: "easy",
    estimated_minutes: 6,
    instructions: "Given a predictable daily spike at a fixed time and steady low traffic otherwise, select the strategy: 'scheduled_autoscaling', 'fixed_capacity', 'manual_scaling_only', or 'no_scaling_needed'.",
    inputs: { pattern: "predictable daily spike at fixed time" },
    expected_output: { answer: "scheduled_autoscaling" },
    workstation_type: "structured_response",
    verification_type: "rule_based",
    verification_definition: { rules: [{ field: "answer", equals: "scheduled_autoscaling" }] },
    points: 10,
    explanation: "Since the spike time is known and predictable, scheduled autoscaling (pre-scaling capacity up just before 8 PM and back down after) handles the load without the waste of fixed 24/7 capacity or the risk of reactive-only scaling lagging behind a sharp, sudden spike.",
    tags: ["cloud", "scaling", "infrastructure"],
  },
  {
    stream: "it",
    competency_area: "Systems Administration",
    skill: "Process Troubleshooting",
    challenge_type: "diagnosis",
    title: "Choose the Correct First Diagnostic Step for a Runaway Process",
    scenario: "A production server's load average has spiked sharply. Checking running processes shows one single process consistently using 98% CPU while every other process remains idle.",
    mission: "Choose the correct first diagnostic step.",
    learning_objective: "Prioritize investigation over disruptive action when a root cause is not yet understood.",
    difficulty: "easy",
    estimated_minutes: 6,
    instructions: "Given one process is pinning CPU at 98% while everything else is idle, select the first step: 'identify_and_investigate_the_process', 'reboot_immediately', 'ignore_it', or 'increase_swap_space'.",
    inputs: { symptom: "one process at 98% CPU, others idle" },
    expected_output: { answer: "identify_and_investigate_the_process" },
    workstation_type: "log_investigation",
    verification_type: "rule_based",
    verification_definition: { rules: [{ field: "answer", equals: "identify_and_investigate_the_process" }] },
    points: 10,
    explanation: "Before taking any disruptive action like rebooting, the correct first step is to identify what the runaway process is actually doing (via top/ps/strace/logs) — rebooting blindly loses the diagnostic opportunity and the issue may simply recur right after restart.",
    tags: ["it", "systems-administration", "troubleshooting"],
  },
  {
    stream: "it",
    competency_area: "Databases",
    skill: "Query Performance Diagnosis",
    challenge_type: "diagnosis",
    title: "Diagnose the Cause of a Slow Database Query",
    scenario: "A query filtering a 5-million-row `orders` table by `customer_email` takes 8 seconds to run. An equivalent query filtering by the primary key `order_id` on the same table returns instantly. `customer_email` has no index.",
    mission: "Identify the most likely cause of the slow query.",
    learning_objective: "Connect index absence on a large table to full-table-scan query performance symptoms.",
    difficulty: "easy",
    estimated_minutes: 8,
    instructions: "Given the slow query filters an unindexed column on a large table while the fast query uses the primary key, select the cause: 'missing_index', 'network_latency', 'insufficient_ram', or 'wrong_query_syntax'.",
    inputs: { tableRows: 5000000, slowColumn: "customer_email (no index)", fastColumn: "order_id (primary key)" },
    expected_output: { answer: "missing_index" },
    workstation_type: "structured_response",
    verification_type: "rule_based",
    verification_definition: { rules: [{ field: "answer", equals: "missing_index" }] },
    points: 10,
    explanation: "Without an index, the database must scan all 5 million rows (a full table scan) to find matches on customer_email, while the primary-key lookup uses its index for near-instant access — the fix is adding an index on customer_email.",
    tags: ["it", "databases", "query-performance"],
  },

  // ─── MCA ──────────────────────────────────────────────────────────────
  {
    stream: "mca",
    competency_area: "Programming",
    skill: "String Processing",
    challenge_type: "implementation",
    title: "Find the First Non-Repeating Character in a String",
    scenario: "A text-processing utility needs a function that identifies the first character in a string that does not repeat anywhere else in that string — a common building block for tokenizer and log-parsing utilities.",
    mission: "Implement a function that returns the first non-repeating character in a given string, or '_' if none exists, and print the result.",
    learning_objective: "Correctly implement a frequency-count-based string algorithm.",
    difficulty: "easy",
    estimated_minutes: 10,
    instructions: "Implement `firstNonRepeating(s)` for the input \"swiss\" and print its result on one line.",
    inputs: {
      starterCode: "function firstNonRepeating(s) {\n  // TODO: implement\n}\nconsole.log(firstNonRepeating(\"swiss\"))",
      language: "javascript",
    },
    expected_output: { stdout: "w" },
    workstation_type: "coding",
    verification_type: "test_cases",
    verification_definition: { language: "javascript", testCases: [{ expectedStdout: "w" }] },
    points: 10,
    explanation: "In \"swiss\": s appears 3 times, w appears once, i appears once — w is the first character (by position) that appears exactly once.",
    tags: ["programming", "strings", "frequency-count"],
  },
  {
    stream: "mca",
    competency_area: "Databases",
    skill: "SQL Aggregation",
    challenge_type: "data_interpretation",
    title: "Find Departments With Above-Average Headcount",
    scenario: "An HR system tracks employees per department. Management wants to know which departments are overstaffed relative to the company average.",
    mission: "Write a SQL query that returns department names with more employees than the average department headcount.",
    learning_objective: "Use a subquery/aggregate comparison — a step beyond a plain GROUP BY.",
    difficulty: "medium",
    estimated_minutes: 10,
    instructions: "Query the `employees` table (columns: id, name, department) to find departments whose employee count exceeds the average employee count per department across all departments.",
    inputs: {
      dataset: {
        tableName: "employees",
        columns: ["id", "name", "department"],
        rows: [[1, "A", "Engineering"], [2, "B", "Engineering"], [3, "C", "Engineering"], [4, "D", "Sales"], [5, "E", "Sales"], [6, "F", "HR"]],
      },
    },
    expected_output: { columns: ["department"], rows: [["Engineering"]] },
    workstation_type: "sql",
    verification_type: "sql_result",
    verification_definition: {
      dataset: { tableName: "employees", columns: ["id", "name", "department"], rows: [[1, "A", "Engineering"], [2, "B", "Engineering"], [3, "C", "Engineering"], [4, "D", "Sales"], [5, "E", "Sales"], [6, "F", "HR"]] },
      expectedResult: { columns: ["department"], rows: [["Engineering"]] },
      matchMode: "unordered_rows",
    },
    points: 15,
    explanation: "Average headcount per department = 6 employees / 3 departments = 2. Engineering has 3 (above average); Sales has 2 and HR has 1 (at or below average). Only Engineering qualifies.",
    tags: ["databases", "sql", "aggregation"],
  },
  {
    stream: "mca",
    competency_area: "Testing",
    skill: "Test Case Design",
    challenge_type: "investigation",
    title: "Identify the Missing Critical Test Case for a Division Function",
    scenario: "A function `divide(a, b)` returns `a / b`. The existing test suite covers: dividing two positive integers, dividing a positive by a negative number, and dividing two negative numbers. There is no test for the case where `b` is 0.",
    mission: "Identify which critical edge case is missing from the test suite.",
    learning_objective: "Recognize division-by-zero as the single most important missing edge case for any division function.",
    difficulty: "easy",
    estimated_minutes: 6,
    instructions: "Given the described test coverage, select the missing critical edge case: 'division_by_zero', 'negative_numbers', 'decimal_numbers', or 'large_numbers'.",
    inputs: { existingTests: ["positive/positive", "positive/negative", "negative/negative"] },
    expected_output: { answer: "division_by_zero" },
    workstation_type: "structured_response",
    verification_type: "rule_based",
    verification_definition: { rules: [{ field: "answer", equals: "division_by_zero" }] },
    points: 10,
    explanation: "Division by zero is undefined behavior (or produces Infinity/NaN depending on the language) and is the single most critical edge case for any division function — its absence from the test suite is a serious gap, more urgent than the other listed options which are already partially covered by the described tests.",
    tags: ["testing", "edge-cases", "test-design"],
  },
  {
    stream: "mca",
    competency_area: "APIs",
    skill: "REST API Design",
    challenge_type: "diagnosis",
    title: "Diagnose Incorrect HTTP Status Code Usage in an API",
    scenario: "A REST API's `GET /users/:id` endpoint returns HTTP status 200 with a JSON body `{ \"error\": \"User not found\" }` whenever the requested user does not exist, instead of a non-2xx status code.",
    mission: "Identify the correct HTTP status code this endpoint should return instead.",
    learning_objective: "Apply REST status-code conventions to a concrete API design flaw.",
    difficulty: "easy",
    estimated_minutes: 6,
    instructions: "For a GET request to a resource that does not exist, the correct convention is HTTP 404 Not Found. Submit '404' as the answer.",
    inputs: { currentBehavior: "returns 200 with error message body for missing resource" },
    expected_output: { answer: "404" },
    workstation_type: "structured_response",
    verification_type: "rule_based",
    verification_definition: { rules: [{ field: "answer", equals: "404" }] },
    points: 10,
    explanation: "Returning 200 OK for a missing resource breaks REST conventions and misleads clients (and caching/monitoring layers) into treating a failure as success. The correct status for 'resource does not exist' is 404 Not Found.",
    tags: ["apis", "rest", "http-status-codes"],
  },
]
