import type { WorkspaceConfig } from '@capabilio/types';

export const softwareEngineerFrontendWorkspace: WorkspaceConfig = {
  type: 'software_engineer_frontend',
  name: 'Frontend Engineer Workspace',
  description: 'Professional frontend development environment with code editor, live preview, and debugging tools.',
  supportedLanguages: ['javascript', 'typescript', 'html', 'css', 'json'],
  defaultLanguage: 'typescript',
  features: ['code_execution', 'test_runner', 'terminal', 'browser_preview'],
  panels: [
    {
      id: 'file-tree',
      type: 'file_tree',
      title: 'Explorer',
      position: 'left',
      defaultWidth: 18,
      isResizable: true,
      isCloseable: false,
    },
    {
      id: 'code-editor',
      type: 'code_editor',
      title: 'Editor',
      position: 'center',
      defaultWidth: 52,
      isResizable: true,
      isCloseable: false,
    },
    {
      id: 'browser-preview',
      type: 'browser_preview',
      title: 'Preview',
      position: 'right',
      defaultWidth: 30,
      isResizable: true,
      isCloseable: true,
    },
    {
      id: 'console',
      type: 'console',
      title: 'Console',
      position: 'bottom',
      defaultHeight: 30,
      isResizable: true,
      isCloseable: true,
    },
    {
      id: 'terminal',
      type: 'terminal',
      title: 'Terminal',
      position: 'bottom',
      defaultHeight: 30,
      isResizable: true,
      isCloseable: true,
    },
    {
      id: 'problems',
      type: 'problems',
      title: 'Problems',
      position: 'bottom',
      defaultHeight: 30,
      isResizable: true,
      isCloseable: true,
    },
  ],
};
